### ISSUE TITLE
Add mention support

### ISSUE THREAD

**Issue by ryanjduffy** [replayio/devtools#3211]
* [ ] Add usernames to users so they can be mentioned
* [ ] Fix mention plugin
* [ ] Add email notifications for mentions

**Comment by jcmorrow** [comment]
@gideonred I feel very silly here but I can't figure out how to get this issue out of the Roadmap and into our new sprint board. Halp?

**Comment by jcmorrow** [comment]
I think it would *definitely* make sense when implementing the socket part of #5572 to have an eye towards using it for other things at least. It should be "implement a socket for multi-player", not "implement a socket for messages" IMO.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-119](https://linear.app/replay/issue/FE-119/add-mention-support)
