### ISSUE TITLE
Column breakpoints

### ISSUE THREAD

**Issue by gideonred** [replayio/devtools#3828]
### Discussed in https://github.com/RecordReplay/devtools/discussions/3743

<div type='discussions-op-text'>

<sup>Originally posted by **jasonLaster** September 25, 2021</sup>
Column breakpoints are currently disabled by default, but available by toggling `app.features.columnBreakpoints`. 

Next steps:
1. audit column breakpoint positions
2. audit ux

 💡  This is really close</div>

**Comment by jasonLaster** [comment]
The core UX challenge of column breakpoints is how do we unify breakpoints and column breakpoints while still keeping them decoupled

<img width="787" alt="Screen Shot 2022-05-24 at 8 27 39 AM" src="https://user-images.githubusercontent.com/254562/170073842-1b019c72-47ee-45af-a4be-c72f003cb070.png">

https://www.loom.com/share/529476aa0d094cc6a56cab6431d827d2

Figma
https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=12451%3A95054
