### ISSUE TITLE
Console groups

### ISSUE THREAD

**Issue by gideonred** [replayio/devtools#3836]
### Discussed in https://github.com/RecordReplay/devtools/discussions/2373

<div type='discussions-op-text'>

<sup>Originally posted by **jasonLaster** April 16, 2021</sup>
https://developer.mozilla.org/en-US/docs/Web/API/Console/group</div>

---

Support for `console.group` and `console.groupEnd()` indentation controls.

**Comment by jasonLaster** [comment]
Moving to december so we can focus on Net Monitor

**Comment by gideonred** [comment]
This ticket has been moved to [FE-121](https://linear.app/replay/issue/FE-121/console-groups)
