### ISSUE TITLE
Stack Trace Select Frame

### ISSUE THREAD

**Issue by jaril** [replayio/devtools#5108]
The Network Monitor Stack Trace panel currently shows the call stack that lead to the request.

The problem is that selecting a frame in the stack navigates to the location, but does not seek to that point in time. We have all the data we need for this to work, but we will need to refactor some redux internals to make it work.

(Created from the [Replay Roadmap Airtable](https://airtable.com/appSzSiRS6UdFlXKj/tblpTtDTV98hPX4m0/viwyIRSTFuDV9bzCx?blocks=hide))

**Comment by abstractalgo** [comment]
Need more info on this.

**Comment by abstractalgo** [comment]
> The Network Monitor Stack Trace panel currently shows the call stack that lead to the request
It does? Where?

I still need some video/image explaining what would a desired outcome actually be. 😬 

> what "Redux internals refactoring" is needed here
I guess, syncing (exposing) selected state of the Network Monitor and global state for the ThreadFront so that all the other components can sync to a new point in the timeline as well.

**Comment by jasonLaster** [comment]
Here's a replay and a loom. It looks like we don't actually need to change that much which is nice

https://app.replay.io/recording/stack-trace-vs-call-stack--0e11f745-1a2e-46eb-b2b8-229c18f0906d?point=51922968606796385171390297007980646&time=20577.822452036922&hasFrames=true

https://www.loom.com/share/7e87f90c5f9f404581591450370b9533

**Comment by jcmorrow** [comment]
I'm going to leave this open but move it out of the current sprint. The stack trace in net monitor was completely broken for a month and no one said anything. This makes me think that spending time fixing a nuance in how that component works isn't worth it. And, I dug into this and it was not (as far as I could tell) a 5 minute change like I was hoping it would be. Another random thought: if we had a new contributor who wanted to dig into how we do time travel things in devtools this might be a good intro card for them?

**Comment by jaril** [comment]
> I'm going to leave this open but move it out of the current sprint. The stack trace in net monitor was completely broken for a month and no one said anything. This makes me think that spending time fixing a nuance in how that component works isn't worth it. And, I dug into this and it was not (as far as I could tell) a 5 minute change like I was hoping it would be. Another random thought: if we had a new contributor who wanted to dig into how we do time travel things in devtools this might be a good intro card for them?

Makes sense. There's a few contributors getting used to the codebase I'll keep an eye out and see if they want to take this on (or at least pair on it then have them finish it up)!

**Comment by jasonLaster** [comment]
Definitely - this would be a great intro to how redux pause state is handled. Not a five minute project (closer to ~8hrs).
