### ISSUE TITLE
Add incremental SSR invalidation

### ISSUE THREAD

**Issue by ryanjduffy** [replayio/devtools#5395]
This'll help us refresh when the recording changes (e.g. when it's made public, initialized, or the title changes)

https://nextjs.org/blog/next-12-1#on-demand-incremental-static-regeneration-beta

**Comment by jasonLaster** [comment]
This feels more like an important issue than a project to me.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-127](https://linear.app/replay/issue/FE-127/add-incremental-ssr-invalidation)
