### ISSUE TITLE
Add e2e test for ReactDevTools

### ISSUE THREAD

**Issue by hbenl** [replayio/devtools#5533]

**Comment by jaril** [comment]
Testing:
- node picker works
- props get shown after we select a node
- highlighting works when you hover over a node
- it shouldn't crash when you go to the beginning of the recording (react devtools open or not)

**Comment by jaril** [comment]
Wait until we're playwrighted!

**Comment by hbenl** [comment]
#6726 reenables the existing test, it already tests showing the props of the selected node and highlighting. It should be updated to also test the node picker and what happens when seeking to the beginning of the recording.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-128](https://linear.app/replay/issue/FE-128/add-e2e-test-for-reactdevtools)
