### ISSUE TITLE
Debug line is highlighted twice

### ISSUE THREAD

**Issue by hbenl** [replayio/devtools#5675]
![Screenshot_2022-03-08_17-53-50](https://user-images.githubusercontent.com/16060807/157286570-7531934e-8b30-4bbb-97e3-c7be1e8e9ad6.png)

STR:
- set and jump to a logpoint
- click on the original source toggle twice

**Comment by jasonLaster** [comment]
@hbenl can you include a replay

**Comment by jaril** [comment]
It might not have happened before because the selection was unknown to codemirror at first load. But it knows it when you're toggling the source.

**Comment by jaril** [comment]
@hbenl Having difficulty getting a replay — mind getting me one?

**Comment by hbenl** [comment]
https://app.replay.io/recording/double-debug-line-highlight--b01cea2d-1227-46d4-968b-bfc337afcd38

**Comment by hbenl** [comment]
It may be as simple as removing this:
https://github.com/RecordReplay/devtools/blob/15711c710f91bb40d891c36f21c1ba32a1eed86b/src/devtools/client/debugger/src/components/Editor/DebugLine.js#L68-L72

**Comment by gideonred** [comment]
This ticket has been moved to [FE-129](https://linear.app/replay/issue/FE-129/debug-line-is-highlighted-twice)
