### ISSUE TITLE
We incorrectly indicate which network request(s) we're paused on

### ISSUE THREAD

**Issue by jaril** [replayio/devtools#5769]
Sometimes a request that has a rewind/fast-forward will not show its rewind/fast-forward button, depending on where you are currently paused.

https://app.replay.io/recording/hello-react--3620f8b3-9bce-41c5-a74b-f9f2372d390c

**Comment by jaril** [comment]
On a side note it'd be nice to see some indication of which rows you can navigate to :)

**Comment by jaril** [comment]
This one's not very straightforward.

It appears that we associate a network request with its triggerPoint's `time` (in ms). Since network requests are fast, it's possible for multiple network requests to have the same `time`. This looks to be a thing that would occur more frequently here than say, console messages/hits.

The problem is it's possible to be paused on request #8, which has the same `time` as request #5-#10. But since we only indicate that we're "paused" on request #8, the user might think that request 5-7 are before 8, and request 9-10 are after 8. They might try to navigate there, but won't be able to because there won't be a rewind/fast-forward button since it's for the same time. But the UI might be confusing because it gives off the impression that you can only be paused on one network request at a time.

@jonbell-lot23 might be worth talking through this quickly later.

<img width="842" alt="image" src="https://user-images.githubusercontent.com/15959269/161989948-bf1079f4-9285-479f-a38f-ad7c4ae0e14f.png">

**Comment by jaril** [comment]
Changed the title so this issue makes more sense.

**Comment by jonbell-lot23** [comment]
@jaril and @jonbell-lot23 talked about this and we're going to address next sprint. Also going to include @jcmorrow .

We put together a [simple Figma page](https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/?node-id=11145%3A65432) to start sketching stuff.

**Comment by jonbell-lot23** [comment]
Ok! @jcmorrow @jonbell-lot23 and @jcmorrow had a good chat and here's where we landed.

1. We should re-use the comments visual treatment with a vertical fuchsia stripe along the left-hand side
2. Separately, there's a task to make sure we think through forward/backward actions. [Find it here](https://github.com/RecordReplay/devtools/issues/6341)

**Comment by gideonred** [comment]
This ticket has been moved to [FE-130](https://linear.app/replay/issue/FE-130/we-incorrectly-indicate-which-network-requests-were-paused-on)
