### ISSUE TITLE
Copying out of the output panel gives bad results

### ISSUE THREAD

**Issue by jassmith** [replayio/devtools#5948]
![image](https://user-images.githubusercontent.com/30443/159801362-5c7a57c5-1381-4247-b91c-b9dac9b99dd9.png)

results in this when copied

```​
0
: 
36
​
1
: 
104
​
2
: 
103
​
3
: 
81
​
4
: 
189
​
5
: 
231
​
6
: 
137
​
7
: 
99
​
8
: 
99
​
9
: 
99
​
10
: 
99
​
11
: 
106
​
12
: 
106
​
13
: 
106
```

**Comment by jaril** [comment]
This might be a place to have a copy JSON object option in a context menu.

**Comment by jaril** [comment]
JSON.stringify takes an indent arg

**Comment by gideonred** [comment]
This ticket has been moved to [FE-135](https://linear.app/replay/issue/FE-135/copying-out-of-the-output-panel-gives-bad-results)

**Comment by markerikson** [comment]
We did implement a "Copy" context menu item for the Object Inspector.
