### ISSUE TITLE
Add an E2E test for breakpoint navigation

### ISSUE THREAD

**Issue by jasonLaster** [replayio/devtools#6101]
**Description:**
We should extend one of our print statement tests to also exercise the next/prev and timeline marker functionality.

**Comment by jaril** [comment]
Holding off on e2e tests til we get playwrighted

**Comment by gideonred** [comment]
This ticket has been moved to [FE-137](https://linear.app/replay/issue/FE-137/add-an-e2e-test-for-breakpoint-navigation)
