### ISSUE TITLE
Source file tabs behave badly when number of tabs overflows horizontal space

### ISSUE THREAD

**Issue by markerikson** [replayio/devtools#6207]
**Description:**

You can open up multiple source files, and each source file opens up in a separate tab.  But, once the number of tabs overflows the available horizontal space in that panel, there's no way to scroll or see a list of already-open tabs.  You've got to hit CTRL-P and re-find the same file again.

**Steps to Reproduce:**

Open up 10 different source file tabs in the DevTools

**Expected Result:**

There should be a button similar to VS Code's "already open files" dropdown that lists files you have open, so you can switch back and forth.

**Additional Context:**

* Screenshots:

Existing UI:

![image](https://user-images.githubusercontent.com/1128784/161827575-a7531e95-8161-4bc5-a266-8dd973ab03bf.png)

VS Code's "Show Opened Editors" command list:

![image](https://user-images.githubusercontent.com/1128784/161827777-bd32ac6c-52f2-4526-b4d5-0b09056e39ac.png)

**Comment by Andrew-Doghry** [comment]
hi can i contribute to this issue. Is it still available ?

**Comment by anikdhabal** [comment]
I guess This problem has been solved and there is a three dot option called show opened files.

**Comment by Rohan-Dah** [comment]
Heyy guys... Is the issue resolved? Cuz if not, I'll be happy to work on it

**Comment by bvaughn** [comment]
This issue was already fixed. Sorry!
