### ISSUE TITLE
Clicking Use Sourcemaps doesn't work while you're paused on a hit for a location in that file

### ISSUE THREAD

**Issue by jaril** [replayio/devtools#6285]
[Replay of the bug](https://app.replay.io/recording/use-sourcemap-click-bug--fed936ac-f1f9-4447-bbc4-f39911dda46f)
[Walkthrough](https://www.loom.com/share/773f06aca0ee4358a722260b63be3d27)

**Comment by gideonred** [comment]
This ticket has been moved to [FE-143](https://linear.app/replay/issue/FE-143/clicking-use-sourcemaps-doesnt-work-while-youre-paused-on-a-hit-for-a)
