### ISSUE TITLE
Investigate replacing Tip Tap with Lexical

### ISSUE THREAD

**Issue by bvaughn** [replayio/devtools#6366]
I dug into our comments code as part of investigating #6138. After digging in, I'm not super thrilled with how Tip Tap works within a React app (e.g. https://github.com/RecordReplay/devtools/issues/6138#issuecomment-1096891604). I think it would be worth looking into replacing it with [Lexical](https://www.lexical.dev/) ([github.com/facebook/lexical](https://github.com/facebook/lexical)). Lexical was designed to work well with React specifically, and a lot of focus was put into making it super performant and accessible.

**Comment by jcmorrow** [comment]
I think my primary investigation would center around this piece: https://github.com/facebook/lexical/blob/main/examples/decorators.md since we have lots of plans for the future of the editor (mentions, tighter integrations with external platforms, etc). Also - I know that there are some open PR's on tiptap to improve React integration - https://github.com/ueberdosis/tiptap/pull/2626 and https://github.com/ueberdosis/tiptap/pull/2562 - which might improve some parts of the TipTap internal without us having to put in the effort to switch over to another editor.

**Comment by bvaughn** [comment]
> I think my primary investigation would center around this piece: https://github.com/facebook/lexical/blob/main/examples/decorators.md since we have lots of plans for the future of the editor

Yup, great call out. Lexical _is_ extensible, although I can't attest to how easy it is or how well it works.

> I know that there are some open PR's on tiptap to improve React integration - https://github.com/ueberdosis/tiptap/pull/2626 and https://github.com/ueberdosis/tiptap/pull/2562 - which might improve some parts of the TipTap internal without us having to put in the effort to switch over to another editor.

Those PRs don't look like they change the Tip Tap / React integration in a fundamental way, unless I'm misreading them.

**Comment by trueadm** [comment]
Please feel free to reach out to the Lexical team, either on our github or discord and we can help you folks wherever possible! :)

**Comment by jcmorrow** [comment]
> Those PRs don't look like they change the Tip Tap / React integration in a fundamental way, unless I'm misreading them.

Yeah maybe I was too optimistic about the problems these solve. I saw [this `requestAnimationFrame` deleted](https://github.com/ueberdosis/tiptap/pull/2626/files#diff-13acb5e551812e195c1140c10ba5ac298a0005996d07756cfd77c2d4194cb350L20-L26) and was hopeful that it could solve some of our issues, but I didn't realize that it's just shuffling stuff around to a different hook 🙁

**Comment by bvaughn** [comment]
Thanks @trueadm!

If you're looking for feedback, I think the most helpful thing you all could do at the moment would be to fill in docs pages like [extending nodes](https://lexical.dev/docs/concepts/extending-nodes). That's a use case we'd be looking to do up front.

I looked at the [example playground](https://codesandbox.io/s/lexical-plain-text-example-forked-qdxhy?from-embed) but it seemed kind of sparse. (For example, it only operates if the entire content is a match. How would you do a substring?)

**Comment by trueadm** [comment]
@bvaughn Sure, I'll look into that today.

Have you seen our playground here? https://lexical-playground.vercel.app/

All the code is on github, but you could take a look at the mentions/hashtags plugin? We also have a hook that might be of use `useLexicalTextEntity`. Which is exported from `@lexical/react/useLexicalTextEntity`.

**Comment by BrianHung** [comment]
> Those PRs don't look like they change the Tip Tap / React integration in a fundamental way, unless I'm misreading them.

Would try using [use-sync-external-store](https://www.npmjs.com/package/use-sync-external-store) to maybe build a custom TipTap + React integration? I think originally `forceUpdate` was a workaround putting `editorState` into a React context, but not being able to use a selector a-la Redux to avoid selectively re-rendering depending on the derived state.

TipTap was initially Vue only in 1.0 which might explain the simple React integration for 2.0. Cheers!

**Comment by trueadm** [comment]
@bvaughn We've updated the docs for extending nodes. https://lexical.dev/docs/concepts/extending-nodes

There are still some TODOs that we will fill in once we get the chance, but hopefully that helps!

**Comment by markerikson** [comment]
Done!
