### ISSUE TITLE
Add details pane to Library

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/devtools#6384]
**Background**

While exploring [Design Library 1.5](https://github.com/RecordReplay/devtools/issues/6265), it was clear that we have three different changes, which I've split into three GitHub tasks:

* Add details pane to library (this issue)
* [Add filters to library](https://github.com/RecordReplay/devtools/issues/6382)
* [Create CI-specific library design](RecordReplay/design#8)

**Implementation notes**
I kept these changes as targeted as possible for now. Once this goes live, we can investigate cool stuff like pulling in comments. But in the meantime this is an MVP version that we can iterate on. See the loom for more details.

**Current design**
![image](https://user-images.githubusercontent.com/9154902/163295341-d58e610f-9776-4b0f-a4db-5b03e7181c1b.png)

**Proposed design**
![image](https://user-images.githubusercontent.com/9154902/163295397-332a2d7f-2822-4da4-87c6-252a1aafb313.png)

**Resources**
Loom: https://www.loom.com/share/8766fe1dbbc840b0b8fc84bea97534db
Figma: https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=11315%3A79656

**Comment by gideonred** [comment]
This ticket has been moved to [FE-147](https://linear.app/replay/issue/FE-147/add-details-pane-to-library)
