### ISSUE TITLE
The library is shown before the onboarding modal

### ISSUE THREAD

**Issue by jasonLaster** [replayio/devtools#6403]
STR:
1. Open replay as a new user
2. notice how the library flashes momentarily

This is fairly easy to reproduce by updating the IF statement in the effect to be true

https://app.replay.io/recording/initial-load--638d7723-e238-4574-a519-3944178ac9e4?point=6814889628629178182488377983500923&time=2694.537017205683&hasFrames=true

**Comment by jonbell-lot23** [comment]
Going through UI polish tasks and adding comments:

This fell through the cracks, let's take it back up. It's an important issue to get right.

**Comment by jaril** [comment]
@souporserious this may or may not be related to the loading things you're looking at this week, so piling it on. Not assigning it to the current sprint though, since onboarding's not #1 currently!

**Comment by ashwinkhode** [comment]
Hey @jaril I made a PR for this issue. Sorry for giving PR out of the blue I was going through the issues and this seemed easy so fixed it. Let me know if there are any changes need to be made in the PR. :)

PR : https://github.com/replayio/devtools/pull/7100

**Comment by jonbell-lot23** [comment]
@ashwinkhode Replay's designer thanks you! This is really helpful!
