### ISSUE TITLE
Only show Print Statement Tooltips on hover

### ISSUE THREAD

**Issue by jasonLaster** [replayio/devtools#6419]
**Description:**

 The panel tooltips (add/remove) (hit count) should hide when not currently hovered [replay](https://app.replay.io/recording/your-first-replay--611c1587-916b-4ab3-a264-3b2b81b54b32)

We mostly do this now, but there are some edge cases that are preventing us from doing this consistently. We can probably borrow some strategies from [here](https://cs.github.com/RecordReplay/devtools/blob/bc81b97496e292c514521601602aef9c88b31196/src/devtools/client/debugger/src/components/shared/Popover.js#L60-L85)

**Comment by jaril** [comment]
> I am struggling to repro this one.

Same. Not sure exactly why this interaction was as bad as it was in that replay but it seems to work just fine now. 

I'm inclined to just close this since the main issue's gone away for now — thoughts?

**Comment by bvaughn** [comment]
The "fix" for this feels pretty heavy handed. Also tempted to close it for now.

**Comment by bvaughn** [comment]
Closing this for now as per the above discussion. If we choose to pick it up later, the direction I think we should take is basically this:
* In `ToggleWidgetButton`, add a document level "mousemove" event handler. Every time a "mousemove" event fires, update a local variable with the current time.
* Also add an interval that periodically checks to see if the most recent mouse move event was longer than some threshold. (Note this check indicates either that the user isn't doing anything _or_ what we missed a leave event, so it might trigger a false positive.)
* If the threshold is exceeded, set the hovered line number to `null` until/unless the mouse moves again.
