### ISSUE TITLE
When you add two collaborators, it gets cleared

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/devtools#6431]
Auto-generated from product office hours chat

Apologies @jasonLaster I forgot the details here. Do you recall this issue and how to reproduce it?

**Comment by jaril** [comment]
@jasonLaster do you remember how to do this/get a replay?

**Comment by jaril** [comment]
@jasonLaster got repro steps??

**Comment by gideonred** [comment]
This ticket has been moved to [FE-150](https://linear.app/replay/issue/FE-150/when-you-add-two-collaborators-it-gets-cleared)
