### ISSUE TITLE
We need a special page for "Are you ready?"

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/devtools#6437]
**Problem**

This is an extremely common screen, and it has a lot of visual problems. 

<img width="547" alt="image" src="https://user-images.githubusercontent.com/9154902/163764134-16982f5e-4173-4282-9fea-7e2a6d3f7787.png">

**Request**

As we're seeing elsewhere in our code, this might be an example of being overly templated, because a design like this isn't currently possible:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/9154902/163764868-a9e991ad-db49-43ae-9a41-f9b98b3982c5.png">

**Next steps**

I'd like this particular screen to be fully customisable. This is not the final visual design, but we do know that whatever design we end up with will require a completely different component than the standard dialog one we're using.

**Comment by jonbell-lot23** [comment]
Similar to https://github.com/RecordReplay/devtools/issues/5785, I'm using a new tag called "design-needs-codehelp" which I'll be using to illuminate things that perhaps need to be rewritten in order to add new design magic

**Comment by jaril** [comment]
Have this in April but not sure how we should prioritize. Let me know @jonbell-lot23

**Comment by jonbell-lot23** [comment]
It falls into the bucket of "design keeps hitting walls" and also general polish/tone.

From a design standpoint, items like this are pretty high priority. But in the end, yeah, it's a back to the future illustration. So less important than things breaking outright.

**Comment by jasonLaster** [comment]
Wonder if this would be a fun initial Travis issue :P

**Comment by jaril** [comment]
@souporserious i'm sticking it in the next sprint for you just so we have a reminder to look at it then and prioritize accordingly. Not a todo yet!

**Comment by gideonred** [comment]
This ticket has been moved to [FE-151](https://linear.app/replay/issue/FE-151/we-need-a-special-page-for-are-you-ready)
