### ISSUE TITLE
Make token previews in the editor faster

### ISSUE THREAD

**Issue by jaril** [replayio/devtools#6481]
https://discord.com/channels/779097926135054346/840240266569187380/966273458478669824

We still run evaluations for every time we try to present a token's preview on hover. There might be an optimization here to return that faster, since we have all of that information in the Scopes panel.

**Comment by jaril** [comment]
This would be higher priority but it seems that it's possible to work around it for now (though not ideal)

**Comment by jasonLaster** [comment]
For context, the user is having especially slow evaluations because it's a Node recording
https://github.com/RecordReplay/customer-support/issues/76

**Comment by jaril** [comment]
This is somewhat related to https://github.com/RecordReplay/devtools/issues/6812 so linking that here.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-153](https://linear.app/replay/issue/FE-153/make-token-previews-in-the-editor-faster)
