### ISSUE TITLE
loading bar is shown momentarily

### ISSUE THREAD

**Issue by jasonLaster** [replayio/devtools#6541]
**Description:**

The Replay loading bar is shown for a bit before the uploading screen is shown again. My assumption is that we only show the loading bar after we're done uploading

[replay](https://app.replay.io/recording/react-devtools-loading--a799dd1b-d754-43e4-b627-8ed6b1e42b01?point=11033630825561897196594425302614636&time=4661&hasFrames=false)

**Comment by gideonred** [comment]
This ticket has been moved to [FE-155](https://linear.app/replay/issue/FE-155/loading-bar-is-shown-momentarily)
