### ISSUE TITLE
Accepting multiple team invites can show a weird caching value

### ISSUE THREAD

**Issue by jasonLaster** [replayio/devtools#6568]
### Description

Accepting multiple team invites can cache loading states

https://app.replay.io/recording/accepting-one-team-shows-loading-for-the-others--af52a28f-91d7-46b5-83f4-1ff4fc4c6003?point=39266744999103529691042957142002518&time=15117&hasFrames=false#

**Comment by jaril** [comment]
To triage.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-159](https://linear.app/replay/issue/FE-159/accepting-multiple-team-invites-can-show-a-weird-caching-value)
