### ISSUE TITLE
Restructure how we interact with and store results and errors from the Analysis API

### ISSUE THREAD

**Issue by jcmorrow** [replayio/devtools#6591]
Problems that are hard to solve with our current state shape:

### Context for loading and reloading Analyses

- Right now, analyses don't always get re-run upon loading changes, when the loading/focus state transition from one state to another, sometimes that should trigger re-runs.
- This is probably not going to be *that* common of a requirement, because, for example, if an analysis gets run *once* at the findPoints level, we will know the correct points for the entire recording and every possible focus region of the recording, and if the analysis has run successfully, we will also know the evaluation at those points, so we will not need to requery until the user changes the expression)
  - A note about points vs location: right now we always run analyses by adding the location of the print statement, but we *could* add a subset of points when we know there will be too many to run a full analysis. This is not a top priority, but it will be a requirement for whatever comes out of https://github.com/RecordReplay/design/issues/36 and should be the kind of operation that our changes will support in the future.
- (In a lot of ways, this is going to line up with other work that we're doing under the umbrella of #6590 , because the loading and focus transitions that would cause analyses to re-run, will also trigger other data refetching)

# Tasks which are blocked by this

- [ ] #6851
- [x] #7033 
- [x] #7036

---

### Context for the next cards

- Related to loading states, there is a pretty specific series of lifecycle events for analyses, (some are documented in https://static.replay.io/protocol/tot/Analysis/), and I've tried to capture some of this in an xState machine:

![CleanShot 2022-05-19 at 10 02 31](https://user-images.githubusercontent.com/5903784/169357104-f03fde97-388f-418e-8da0-b1b4cb94070c.png)

[Link](https://stately.ai/viz/9f4a5f8c-4d3c-4baf-aa8c-a483f108771f)
- Wherever we end up in terms of storing analysis states, it should probably roughly align with that state machine
- One way to think about the lifecycle of an analysis, is that it can either be a "partial" analysis, or a "full" analysis, depending on which steps it gets to.
- All analyses will:
  - Be created
  - have something `add`ed to it (you can see which things you can add by looking at the methods inside of the Analysis domain which start with the word `add`.
  - have `findPoints` called, which can error or result in a list of points being emitted, this is a "partial" analysis
  - (maybe) have `runAnalysis` called, which will result in a fork at each of the points and an evaluation of whatever mapper was given during creation. If an analysis gets to this step, it should be considered "full". (fair warning: I find these terms useful, but they are not official).
  - All analyses will also get `release`d after this.
- There are several different decision points during a user's request for a breakpoint, where we might choose to run a partial, full analysis.
  - If an analysis's `findPoints` command has come back with an error, we should definitely not try and run the full analysis, since that is also guaranteed to error.
  - If an analysis's `findPoints` command has come back with a result which we know will generate an error if we try and run a full analysis, we should also not run the full analysis.
  - (We do this part already) If a breakpoint's contents are all primitives, we will want to `findPoints`, but do not need to run a full analysis, until the user gives us a non-primitive statement to evaluate.
- Using the existing backend API, analyses can be cancelled when we no longer care about the result. There are several UI interactions like editing the statement or changing focus window that should cause the running analysis to be cancelled, but right now they do not.
- Right now, a super common point of confusion (I could go back through the git history and point to each time we've tried to fix this, and it would be a lot, but I'll spare you) is that two parts of the analysis lifecycle will return an error with the same phrase "Too many points", but depending on which part of the analysis lifecycle that error came from, it can mean two totally different problems: "Too many points" to run `findPoints` is 10,000. Too many points to run `runAnalysis` is 200, because they have vastly different resource requirements and runtime behaviors on the backend. (Josh to link to an explainer here).

# Tasks

- [x] #6852
- [x] #6853

---

Original ticket content (you can probably ignore)

https://github.com/RecordReplay/design/issues/36 is also about Analysis tools, but this card is specifically about errors. Specifically, two things:

1) Correctly handling error states
2) Knowing when to re-run analyses

In general, we should re-run analyses (and do other necessary data-refetching that is dependent upon load) when:
1) the `loaded` state has just changed *and* 
2) the `loaded` state matches the `loading` state.

See https://github.com/RecordReplay/devtools/issues/6549 for an example of what goes wrong with this right now. And also see https://www.loom.com/share/7b607f774c79470096ca0db38ad03a5a if you want to see a raving lunatic talk about analyses for a few minutes at the end of a long day.

And the replay from that loom: https://app.replay.io/recording/analysis-never-moves-beyond-loading--ff87d6b7-bebd-4c6b-8806-6a4b6e478bb5

**Comment by jaril** [comment]
@jcmorrow I thought this might be related to https://github.com/RecordReplay/devtools/pull/6663 but looks different enough.

Do you still feel like getting around to this in May?

**Comment by jaril** [comment]
Compiling a list of things that we should revisit when this is closed to make sure we circle back to them and resolve them:
- [ ] https://github.com/replayio/devtools/issues/6872

**Comment by gideonred** [comment]
This ticket has been moved to [FE-161](https://linear.app/replay/issue/FE-161/restructure-how-we-interact-with-and-store-results-and-errors-from-the)
