### ISSUE TITLE
Offer different sources with the same URL in the UI

### ISSUE THREAD

**Issue by hbenl** [replayio/devtools#6595]
There may be multiple different sources with the same URL (see RecordReplay/customer-support#69, #3429 and #6594; this usually happens when the recorded app is running in a dev-server and the user changes a source file while recording), but our sources tree and the quick open modal currently only offer one source per URL.
If there are multiple different sources with the same URL, all of them should be accessible.

**Comment by jaril** [comment]
@jonbell-lot23 I think this'll come across your radar already but just in case!

**Comment by jonbell-lot23** [comment]
Thanks @jaril ! So I understand the issue:

1. User edits stuff
2. So we end up with two URLs but we only show one

But I'm having trouble envisioning the location where we'd provide this option. Can someone jot down a quick description of where the option would go and how it could work?

**Comment by hbenl** [comment]
> So we end up with two URLs but we only show one

No, we end up with two different versions of a source with the same URL.
There are several ways we could offer them in our sources tree:
- the different versions of a source could be shown next to each other in the sources tree
- sources with multiple different versions could be expandable (like a folder) and show the versions as children
- a click on a source with multiple different versions could open a popup listing the versions
- a click on a source with multiple different versions could open one of the versions while other versions are offered in a context menu

**Comment by markerikson** [comment]
> the different versions of a source could be shown next to each other in the sources tree

Pretty sure this is how Chrome does it, at least.  But the expandable file entry also sounds good.

**Comment by jasonLaster** [comment]
> the different versions of a source could be shown next to each other in the sources tree

We should probably default to having the same behavior as chrome.

**Comment by jonbell-lot23** [comment]
I have applied all my UX wisdom to determine that we should have the same behaviour as chrome. If you need more UX thinking, please include a screenshot of Chrome in this state for me to react to.

**Comment by jaril** [comment]
Thrown into July since it's not super urgent and edge case-y. To triage then.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-162](https://linear.app/replay/issue/FE-162/offer-different-sources-with-the-same-url-in-the-ui)
