### ISSUE TITLE
Recording photos should be fetched in batch, not serial

### ISSUE THREAD

**Issue by jazzdan** [replayio/devtools#6641]
Currently when we load all of the recordings for a workspace we fetch:

1) Fetch all of the recordings for each workspace
2) For each recording, fetch each of the photos for that recording.

As demonstrated in [this replay](https://app.replay.io/recording/one-query-per-recording-for-pictures--dace8099-cf6b-4ebb-81ca-639ccf3cd426) (which is private because it's a recording of the internal Replay workspace)

Instead we should fetch all of the photos for the initial set of recordings in a batch, then fetch them as needed one at a time. This will reduce network traffic, improving performance for the user, and reduce load on the backend.

**Comment by jaril** [comment]
This sounds like something nice for somebody to pick up this month. It's already assigned to this sprint, so leaving it unassigned for now so we can discuss quickly at standup to see if anybody's up for it.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-164](https://linear.app/replay/issue/FE-164/recording-photos-should-be-fetched-in-batch-not-serial)
