### ISSUE TITLE
Variables show as undefined on hover

### ISSUE THREAD

**Issue by bhackett1024** [replayio/devtools#6665]
Replay with comments:

https://app.replay.io/recording/undefined-hover--bb361ffc-8530-4785-a0d7-88c67338287b?point=95083936234053482513670089570521000&time=33256&hasFrames=false

**Comment by jasonLaster** [comment]
This is a fun issue with how we build the symbols list in `getSymbols`

**Comment by gideonred** [comment]
This ticket has been moved to [FE-165](https://linear.app/replay/issue/FE-165/variables-show-as-undefined-on-hover)
