### ISSUE TITLE
Redux DevTools UI ("v1")

### ISSUE THREAD

**Issue by markerikson** [replayio/devtools#6674]
#6106 covered the initial implementation work for Redux DevTools support.  As of that issue, we now have `gecko-dev` capturing Redux actions as annotations, and a hacky implementation of UI support by actually rendering the real RDT UI components directly in our app.

For v1, we're going to take this in a different direction:

- We'll reuse the main RDT reducer logic, but in our Redux store
- Reuse/modify existing Replay UI panes for actions list / state tabs
- Current RDT UI will be a separate popout tab

Reasons:

We want to keep a common look and feel in Replay's UI. Also, we want to integrate things like the actions list with Replay's behavior - show arrow for current time location, jump to pause or stack trace, etc.

The existing RDT components can't do that as-is.

However, there's also value in having the entire existing Redux DevTools UI still, and we've already shown we can use that.

So, similar to our "Sourcemap Explorer" integration, we'll add a button that pops out the RDT UI as a totally separate browser tab from the main Replay UI.

I'm going to spend a week or so trying to do some cleanup on our codebase ( per #6552 ), and then circle back and start working on the revised Redux DevTools UI implementation.

Jason put up a very pseudo-code-y PR that doesn't at all run, but demonstrates the ideas of where we want to go, over in #6666 .

**Comment by gideonred** [comment]
This ticket has been moved to [FE-167](https://linear.app/replay/issue/FE-167/redux-devtools-ui-v1)
