### ISSUE TITLE
Display debugger step commands shortcuts somewhere else so we can nuke the old shortcuts modal

### ISSUE THREAD

**Issue by jaril** [replayio/devtools#6678]
![image](https://user-images.githubusercontent.com/15959269/162511150-5cdf0848-8381-4995-994d-98b475493d4f.png)

[<ShortcutsModal />](https://github.com/WebReplay/webreplay-devtools/blob/76d9b958dd1f39b821970751a7dc5faa6dc830a8/src/devtools/client/debugger/src/components/ShortcutsModal.js)

Here are our shovel-ready tasks for dev in order to close this out. ([Details on this Notion page](https://www.notion.so/replayio/Decomissioning-our-old-keyboard-shortcuts-menu-9299cc80c53c4514ac8c2a20cfffc76e))

- [ ] Breakpoint buttons need their tooltips to have their keyboard shortcuts*
- [ ] Add these items to command palette
        * Step over
        * Step in
        * Step out
        * Find next
        * Go to line
- [ ] Make those items dynamic based on context. For example, the step actions would be greyed out everywhere except when someone is paused on a breakpoint

* 
<img width="557" alt="image" src="https://user-images.githubusercontent.com/9154902/165662721-e8845334-d78a-44e1-84a6-a262b7290eb6.png">

Two issues here to address:
* This tooltip has a typo
* The other tooltips aren't there and should be

**Comment by jasonLaster** [comment]
@jonbell-lot23 where is the design?

**Comment by jonbell-lot23** [comment]
Not necessary, these are code changes

**Comment by jasonLaster** [comment]
@jonbell-lot23 i guess, the general sentiment is that it would be nice to document our analysis/decisions both for others and posterity.

**Comment by jonbell-lot23** [comment]
@jasonLaster Agree. In this case, the rationale and analysis is in the ticket description, with a link to the original Notion file. It's not something that requires an export from Figma.

**Comment by jasonLaster** [comment]
Thanks. Looks good!

**Comment by gideonred** [comment]
This ticket has been moved to [FE-168](https://linear.app/replay/issue/FE-168/display-debugger-step-commands-shortcuts-somewhere-else-so-we-can-nuke)
