### ISSUE TITLE
Acknowledge when an analysis is taking a long time

### ISSUE THREAD

**Issue by jcmorrow** [replayio/devtools#6681]
It's not uncommon for an analysis to just never return if it has a lot of hits:

https://app.replay.io/recording/why-wont-this-analysis-error--e4afd2e2-e3ab-4df1-b2bf-bcf97df30607?point=69122452082982376440253399919755264&time=47832&hasFrames=false

In this case, we should probably let the user know first:

Hey this is taking a long time, sorry, we're still grokking

and then:

This took so long we canceled it, sorry, maybe try making the analysis smaller with focus mode and try again?

We should be careful with the messaging there in case it's not taking a long time because of the number of hits, although I think generally that will be the case.

**Comment by jcmorrow** [comment]
Realistically this is going to be a follow-on to #6591

**Comment by gideonred** [comment]
This ticket has been moved to [FE-169](https://linear.app/replay/issue/FE-169/acknowledge-when-an-analysis-is-taking-a-long-time)
