### ISSUE TITLE
Try to pick best quote type to avoid quote escaping in an evaluated string

### ISSUE THREAD

**Issue by Andarist** [replayio/devtools#6704]
evaluated strings in the console are always double-quoted and thus double quotes are being always escaped - this is super annoying to me as I copy-paste those results and share them with people, and ofc those `\"` are hurting readability

Chrome's console tries to avoid escaping and selects the wrapping quote type to do so, its default is a single quote, but if we put a single quote in the string then it switches to a double qoute, if we put both in then it goes to backticks, if we finally put ALL 3 of them then it sticks to a single quote and has to escape single quotes

In Chrome:
![image](https://user-images.githubusercontent.com/9800850/167862522-d605020f-83a6-4001-afa0-6278fe50dee8.png)

**Comment by gideonred** [comment]
This ticket has been moved to [FE-170](https://linear.app/replay/issue/FE-170/try-to-pick-best-quote-type-to-avoid-quote-escaping-in-an-evaluated)

**Comment by bvaughn** [comment]
Going to re-triage FE-170 to see if we can't knock this out, but I'm going to close this GH issue in the meanwhile.

**Comment by bvaughn** [comment]
Fixed via #8992
