### ISSUE TITLE
Commenting UX for unauthenticated users

### ISSUE THREAD

**Issue by souporserious** [replayio/devtools#6723]
**Description:**
Right now when filling out a comment and not being signed in yet we destroy the state when coming back. A couple of things that would be nice here:

1. We store the input state in local storage and clear it upon submission.
2. We return the user to the same active comment rather than the first comment.

**Steps to Reproduce:**
1. Type a reply comment.
2. Refresh the screen or sign in and the input state has been lost.

**Expected Result:**
The input should save the last state if it had not been submitted or navigated away from (maybe component unmount is a good heuristic here?).

**Comment by bvaughn** [comment]
> Right now when filling out a comment and not being signed in yet we destroy the state when coming back.

Can we disallow commenting when you're not signed in to reduce the likelihood of this happening?

**Comment by souporserious** [comment]
Sweet, yeah I think keeping comment state in one place is the right call 🚢. And disabling comments when signed out totally makes sense!

**Comment by bvaughn** [comment]
My preference for this issue then is:
* We disallow comments if you're not signed in (assuming we don't already do this).
  * We ignore (for now) the edge case of the session expiring mid-comment.
* We move up the priority of #6566 rather than building anything else on top of it (and then revisit the comment UX then).

**Comment by jasonLaster** [comment]
@bvaughn agreed that it would simplify things to disable drafting a new comment while signed out.

Assume you're not referring to also reading comments for public replays

**Comment by bvaughn** [comment]
Nope! Drafting only.

The latest architecture prototype does this:
* (Published/public) comments are read-only for unauthenticated users
* Authenticated users can reply or edit/delete their own comments
* Draft comments go into GraphQL too and can be published later (by pressing Enter or clicking a "share" button)

**Comment by gideonred** [comment]
This ticket has been moved to [FE-171](https://linear.app/replay/issue/FE-171/commenting-ux-for-unauthenticated-users)

**Comment by bvaughn** [comment]
https://github.com/replayio/devtools/pull/7124
