### ISSUE TITLE
Our video, layout, and picker icons shouldn't have a background highlight

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/devtools#6743]
Loom: https://www.loom.com/share/53643932e2dd4d029eb79bdcb134dd20

See how the icon in the top right has a background colour? The icon itself should light up, but the background shouldn't. The reason this is happening is we're using the same component we use for other tabs. We need a new component that doesn't have the same hover effects.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/9154902/168179978-201b025f-bd8a-4958-be08-b7f05e37a650.png">

**Comment by jonbell-lot23** [comment]
Hi @souporserious ! This is another item I've had on my plate for a while (probably over six months!) but struggled to get working right in the code. Have a sec to take a look?

**Comment by souporserious** [comment]
Yeah, definitely! I'll get this cleaned up! ✨

**Comment by gideonred** [comment]
This ticket has been moved to [FE-173](https://linear.app/replay/issue/FE-173/our-video-layout-and-picker-icons-shouldnt-have-a-background-highlight)
