### ISSUE TITLE
Refactor JSTerm

### ISSUE THREAD

**Issue by hbenl** [replayio/devtools#6778]
`src/devtools/client/webconsole/components/Input/JSTerm.tsx` has some issues:
- it's the cause of #6774
- it contains an unsafe side effect (see https://github.com/RecordReplay/devtools/pull/6775#pullrequestreview-974072746)
- it's really hard to understand how the hooks in the component work together

**Comment by gideonred** [comment]
This ticket has been moved to [FE-175](https://linear.app/replay/issue/FE-175/refactor-jsterm)
