### ISSUE TITLE
open source icon wrong hover color in dark mode

### ISSUE THREAD

**Issue by souporserious** [replayio/devtools#6780]
**Description:**
The event source icon hover color is the wrong color in dark mode.

**Steps to Reproduce:**
In dark mode, hover the event open source action to see it's the wrong color.

**Expected Result:**
Color should be corrected for dark mode.

* Screenshots:
* Video (Loom):
* Replay ([replay.io/record-bugs](https://replay.io/record-bugs) for instructions):

https://user-images.githubusercontent.com/2762082/168648752-3feaf5b5-078f-4815-a8ab-9f8c9afa7b38.mp4

**Comment by gideonred** [comment]
This ticket has been moved to [FE-176](https://linear.app/replay/issue/FE-176/open-source-icon-wrong-hover-color-in-dark-mode)
