### ISSUE TITLE
Typing in the console is really, really, really slow

### ISSUE THREAD

**Issue by jcmorrow** [replayio/devtools#6793]
I don't know if this was something *else* slowing everything else down, or if it was typing in the console itself, but each of these warnings was a keystroke:

![CleanShot 2022-05-16 at 21 01 01](https://user-images.githubusercontent.com/5903784/168726154-fe7560b8-bb80-4dff-9d74-2f657c144bfc.png)

Replay was completely unresponsive for probably 30 seconds or so after I stopped typing.

**Comment by jcmorrow** [comment]
When I tried to reproduce for a Replay, it was not nearly as slow, so I'm not sure what is special about the state of this tab. Anyways, here's a Chrome profile, because that's all I could get.


https://www.dropbox.com/s/e8vqjrk48y79jl9/slow%20key%20presses.json?dl=0

**Comment by markerikson** [comment]
@jcmorrow it's 12:25 AM EST.  Don't tempt me with puzzles like this.

Please.

Aw, drat...

*clicks download link*

**Comment by markerikson** [comment]
First observations:

- Wow, that is a whole lotta reflow or layout or something:

![image](https://user-images.githubusercontent.com/1128784/168729595-d17fa3c6-04e3-41bf-9082-b0e3d46dddec.png)

- I see a `t.componentDidUpdate` in there, followed by a `t.hydrate`.  I don't _think_ that's our code.  And yeah, after doing a set of searches through `node_modules`, I think that is actually `react-codemirror2` itself:

https://github.com/scniro/react-codemirror2/blob/master/src/index.tsx#L420-L443

- The `componentDidUpdate` code is here: https://github.com/scniro/react-codemirror2/blob/master/src/index.tsx#L581-L604

```ts
  public componentDidUpdate(prevProps) {

    if (SERVER_RENDERED) return;

    let preserved: IPreservedOptions = {cursor: null};

    if (this.props.value !== prevProps.value) {
      this.hydrated = false;
    }

    if (!this.props.autoCursor && this.props.autoCursor !== undefined) {
      preserved.cursor = this.editor.getDoc().getCursor();
    }

    this.hydrate(this.props);

    if (!this.appliedNext) {
      this.shared.applyNext(prevProps, this.props, preserved);
      this.appliedNext = true;
    }

    this.shared.applyUserDefined(prevProps, preserved);
    this.appliedUserDefined = true;
  }
```

Working our way back up, `<CodeMirror>` is used in [`ControlledCodeMirror.tsx`](https://github.com/RecordReplay/devtools/blob/f75d608e8ef7148f3ed4e8771ddc251ab870b157/src/ui/components/shared/CodeEditor/ControlledCodeMirror.tsx), which in turn is used in [`EditorWithAutocomplete.tsx`](https://github.com/RecordReplay/devtools/blob/f75d608e8ef7148f3ed4e8771ddc251ab870b157/src/ui/components/shared/CodeEditor/EditorWithAutocomplete.tsx).

I don't have an immediate answer for why just typing is causing the perf issues, but that's at least the chain of components involved.

**Comment by markerikson** [comment]
Sort of related: it looks like `react-codemirror2` is using CodeMirror 5.x (as a peer dep)

https://github.com/scniro/react-codemirror2/blob/master/package.json#L56

and our own `package.json` currently lists `"codemirror": "^5.65.2",`.

Here's a post from Replit talking about the advantages of CodeMirror 6:

https://blog.replit.com/codemirror

Is it possible that upgrading CodeMirror itself might help?  (I realize this might also entail swapping React wrappers.)

**Comment by markerikson** [comment]
More research: CodeMirror 6 appears to not be 100% final yet, and there _is_ a bunch of migration changes because it's a rewrite: https://codemirror.net/6/docs/migration/

I do see https://github.com/tbjgolden/react-codemirror6 as a potential wrapper.

**Comment by jasonLaster** [comment]
@markerikson upgrading to 6 would be a big change. basically a new library

**Comment by markerikson** [comment]
Yeah, that's what I was figuring as I was looking through that migration info.

**Comment by jaril** [comment]
Gonna wrap up the codemirror 6 discussion since that's probably its own discussion.

This is pretty severe if typing in the console is super slow. Anecdotally I haven't seen it so I'm making urgency as low, and it seems like if @markerikson's investigation is correct, the proper fix would take a lot of effort.

Sticking this in icebox unless we find out that it's an easier fix and/or more people/sessions are being affected.

**Comment by jcmorrow** [comment]
@jaril I don't think this should be iceboxed. This happens for me every time I am paused at a place where eager evaluation is possible.

**Comment by jasonLaster** [comment]
Agreed. We should prioritize fixing this edge case, but it seems like it's not a codemirror issue as us terrorizing CM in some way.

**Comment by jaril** [comment]
> Replay was completely unresponsive for probably 30 seconds or so after I stopped typing.

Didn't know that! Bumping it back up and putting it in this sprint for somebody to pick up as soon as I see soft focus/analysis work relax. Or if I make some decent progress on graphql things today I can grab it!

**Comment by gideonred** [comment]
This ticket has been moved to [FE-177](https://linear.app/replay/issue/FE-177/typing-in-the-console-is-really-really-really-slow)
