### ISSUE TITLE
Refactor context menu architecture

### ISSUE THREAD

**Issue by bvaughn** [replayio/devtools#6798]
We have multiple context menu implementations in our project now (see [Loom](https://www.loom.com/share/20ff940adcaa4c52bf457663b84a957b)). The [legacy one](https://github.com/RecordReplay/devtools/blob/master/src/devtools/shared/contextmenu.js) is very imperative and supports only a small set of display options (basically string label with optional image badge) and a [newer, declarative one](https://github.com/RecordReplay/devtools/blob/master/src/ui/components/ContextMenu/) which is more flexible with what it can render.

The new one consists of a fairly reusable base UI component:
https://github.com/RecordReplay/devtools/blob/9088950e556ecbae620cf2aaf3c21c8f68a9263f/src/ui/components/ContextMenu/index.tsx#L11-L21

But it also has what appears to be a generic Redux API:
https://github.com/RecordReplay/devtools/blob/9088950e556ecbae620cf2aaf3c21c8f68a9263f/src/ui/actions/contextMenus.ts#L20-L26

On closer inspection though, this API is only written to be used by a single place:
https://github.com/RecordReplay/devtools/blob/9088950e556ecbae620cf2aaf3c21c8f68a9263f/src/devtools/client/debugger/src/components/Editor/index.js#L261-L281
https://github.com/RecordReplay/devtools/blob/9088950e556ecbae620cf2aaf3c21c8f68a9263f/src/devtools/client/debugger/src/components/Editor/index.js#L421

This means that if anything else tries to use the Redux bits, it will break assumptions in the Editor UI.

That being said, I don't think the Editor UI needs to use Redux for this; it should be able to just move that "state" into React _component state_ and we can just delete that action/reducer pair.

This is actually how the `HeaderGroups` component is using the menu:
https://github.com/RecordReplay/devtools/blob/9088950e556ecbae620cf2aaf3c21c8f68a9263f/src/ui/components/NetworkMonitor/HeaderGroups.tsx#L21-L33

# Action items
- [ ] Remove the legacy implementation and update the half dozen or so current uses to reference the new one.
- [ ] Update the Editor to move context menu data into `state` and delete the action/reducer pair.

**Comment by markerikson** [comment]
Totally agree with moving this away from Redux. 

FWIW I've done Redux-driven context menus before using a couple different approaches, and it's _doable_, but you also end up tying yourself into some restrictions (no functions as props, etc).  I really don't think we need anything like that here.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-179](https://linear.app/replay/issue/FE-179/refactor-context-menu-architecture)
