### ISSUE TITLE
Improve UX for Debugger.getHitCounts - Too many generated locations to perform analysis.

### ISSUE THREAD

**Issue by gideonred** [replayio/devtools#6800]
When using the frontend our users are getting from the backend "Too many generated locations to perform analysis." when the frontend is running Debugger.getHitCounts.

BriahH gave a good description of the probable cause and possible UX improvement (Discord thread: https://discord.com/channels/779097926135054346/975867758719959061):

```
this is related to source maps, there is a limit on how many generated locations we will handle for a single original location to avoid problems we've had in the past where an original location could have many thousands of generated locations and things would break
it's hard to say how much this impacted the user without more information from the frontend, but it's likely to be broken glass
switching to the generated source and setting a breakpoint there should avoid the problem, but that would be a pretty advanced technique
```

Josh agreed that frontend should consider giving the user the advice to switch to the generated source (with link to some documentation?) to enable the user to help themselves around the error message.

**Comment by jasonLaster** [comment]
switching over to @hbenl for source maps support

**Comment by gideonred** [comment]
This ticket has been moved to [FE-180](https://linear.app/replay/issue/FE-180/improve-ux-for-debuggergethitcounts-too-many-generated-locations-to)
