### ISSUE TITLE
User was able to generate 2000 GetActiveSessions requests within a second

### ISSUE THREAD

**Issue by gideonred** [replayio/devtools#6802]
This user generated 2000 GetActiveSessions requests within a second: https://ui.honeycomb.io/replay/datasets/backend/result/BbMGHeqjg23

I suspect a frontend bug?

**Comment by gideonred** [comment]
This wasn't just one user. It seems it's typical for our frontend to request GetActiveSessions a few hundred times per second for a session.

**Comment by jasonLaster** [comment]
Looks like this is a `graphql` call https://cs.github.com/RecordReplay/devtools/blob/7502d4cf4914b880e9322b5167c2a46adee3d0b1/src/ui/components/Header/Header.tsx?q=GetActiveSessions#L31

**Comment by gideonred** [comment]
This ticket has been moved to [FE-181](https://linear.app/replay/issue/FE-181/user-was-able-to-generate-2000-getactivesessions-requests-within-a)
