### ISSUE TITLE
Consider adding an "Exclude `node_modules`" option to the Quick Open dialog

### ISSUE THREAD

**Issue by markerikson** [replayio/devtools#6811]
Per `yeion7` on Discord:

> I have been using Replay for a few days, and this option in the common events panel is one of the most helpful things. I’m wonder if is possible to do that in a global manner. For example, in the files selector, most of the time I’m not searching for a file in node_modules, but right now there are a lot of results of file in it 
> ![image](https://user-images.githubusercontent.com/1128784/168907572-f237a1cf-b44c-4a80-b21e-05fef8b736e6.png)

My thoughts:

I'm actually legitimately not sure if the Quick Open panel's logic supports that right now (as in, I've looked at the code just enough to see that it has a lot of variations in search capability, but I don't know if it has any logic for doing exclusions by path).

It would probably be fairly simple to throw a similar checkbox into that dialog and a bit of filtering logic - really just a question of whether that's the best design approach.

@jonbell-lot23 , any real quick design thoughts on throwing in a checkbox into that dialog vs doing something else?

It also sounds like this may be a thing that could apply to the "Full Text Search" panel as well, where you would want to limit results to only own-app files rather than libraries.  That could alter how we'd want to present this as an option.

**Comment by jonbell-lot23** [comment]
@markerikson 

We decided last time to go with the most brain-dead possible way to include/exclude node modules in search and ended up with this:
![image](https://user-images.githubusercontent.com/9154902/169179885-8e7bde03-df38-4f27-8b88-de20b0f58c60.png)

I'm not sure I'm quite understanding the question here. Is the request around having an "exclude node_modules" option when you're deploying this search?

![image](https://user-images.githubusercontent.com/9154902/169180138-e26e4f23-e6fc-4e10-9590-74a04f1baf81.png)

If so, I could come up with a quick sketch for how we could do that without a ton of effort. Let me know!

**Comment by markerikson** [comment]
Yeah, it is - the `CTRL-P` dialog.  (I think their second half of the question _was_ around full text search, maybe, but as you've shown there it seems like we've got a checkbox for that already?)

**Comment by gideonred** [comment]
This ticket has been moved to [FE-182](https://linear.app/replay/issue/FE-182/consider-adding-an-exclude-node-modules-option-to-the-quick-open)
