### ISSUE TITLE
We should debounce evaluations that are likely to be unused

### ISSUE THREAD

**Issue by jcmorrow** [replayio/devtools#6812]
We send multiple protocol requests for every single term that a user's cursor touches while at a pause in the editor. If they don't keep their cursor there for at least 50 or 100 milliseconds, it does not seem like we should kick off those protocol requests at all.

https://user-images.githubusercontent.com/5903784/168913498-15936516-acfd-46f1-9733-dfd7443f7cdc.mp4

We should also debounce eager evaluations in the console. Right now, if you type `window` in the eager eval as fast as you can, we will fire off 6 different evaluations. We should debounce with some reasonable time period.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-183](https://linear.app/replay/issue/FE-183/we-should-debounce-evaluations-that-are-likely-to-be-unused)
