### ISSUE TITLE
Multi-level console messages are misaligned

### ISSUE THREAD

**Issue by bvaughn** [replayio/devtools#6821]
![Misaligned multi-line console text](https://user-images.githubusercontent.com/29597/169058458-da2fa543-bb41-4d71-8e3d-5d210de00624.png)

I think this is caused by the `white-space: pre-wrap` style set by the `.message-body` class. For some reason, browsers are adding more padding to the first line than subsequent ones.

My first thought was that there was whitespace but `element.textContent` shows that isn't the case.

cc @souporserious if you have ideas here 😄  Otherwise I can dig in later!

**Comment by gideonred** [comment]
This ticket has been moved to [FE-185](https://linear.app/replay/issue/FE-185/multi-level-console-messages-are-misaligned)
