### ISSUE TITLE
Add a "default to devtools" experimental setting

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/devtools#6828]
* New users should always default to Viewer
* Per-replay, we should always default to your last view
* But if someone opts in, they should be able to default to devtools

This request originally came from Tablecheck, I think.

**Comment by jonbell-lot23** [comment]
@markerikson I am assigning this to you cheekily since we were chatting in a thread earlier. No worries assigning to someone else, putting in icebox, whatever! Just getting the ball rolling for discussion.

**Comment by jonbell-lot23** [comment]
CC @jaril this is a small tweak that will bring some joy, so it'd be nice to get it knocked out

**Comment by gideonred** [comment]
This ticket has been moved to [FE-186](https://linear.app/replay/issue/FE-186/add-a-default-to-devtools-experimental-setting)
