### ISSUE TITLE
Add rainbow picker to our console's right-click menu

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/devtools#6840]
Now that we've pushed out our right-click console menu as part of Focus Mode 1.2, we can add the final piece to the puzzle: our rainbow picker.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/9154902/169202567-6a38471f-e435-4731-8375-8af2f71f0a84.png">

Should be self explanatory based on the work we did with Print Statements. If no color is set, a user can change it here. If a color is set, they can change it here.

Note that this screenshot has a darker orange around the orange circle -- that's a planned design but not yet in the CSS. Feel free to add to the CSS to show state, but it's not necessary yet. I have some work to do on animation/states to reconcile elsewhere in the system.

**Comment by jonbell-lot23** [comment]
Hi @bvaughn ! Only assigning this to you for visibility reasons, feel free to push it out, assign to others, etc.

**Comment by jonbell-lot23** [comment]
Hey @jaril I nominate this for higher priority since it ties into the website and the awesome story we're trying to tell

**Comment by jaril** [comment]
It ties into the website, but that new website hasn't landed yet.

Leaving it in the next sprint for now, but I deprioritized some console polish so that there's less things ahead of it.
