### ISSUE TITLE
Share dialog 2.0

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/devtools#6841]
Here's the code issue that's paired with the design ticket!

[Design ticket here](https://github.com/RecordReplay/design/issues/29)
[Loom explaining the design here](https://www.loom.com/share/46086b782f2c452b9069ca738caba192)

![image](https://user-images.githubusercontent.com/9154902/169205497-5ac56095-f0a4-4d73-ae59-08df585a3ba9.png)

**Comment by bvaughn** [comment]
I'm going to optimistically put this issue into the upcoming Sprint, but we can talk about it during the planning meeting 😄

**Comment by bvaughn** [comment]
Seems like we should maybe push this out a sprint or two based on Jason's top vs mid funnel prioritization guidance.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-188](https://linear.app/replay/issue/FE-188/share-dialog-20)
