### ISSUE TITLE
Rerun analyses upon some focus/loaded region changes

### ISSUE THREAD

**Issue by jcmorrow** [replayio/devtools#6851]
### Context

- Right now, analyses don't get re-run upon loading or focus window changes.
- We need to rerun analyses for a location when the *loaded* regions change *and*:
  - The location overflowed while finding points
  - The *loaded* regions that we last ran this location's analysis for have changed such that they are not a subset of previously run analyses. (i.e. there are potentially new points to be found).
- This logic is identical to the logic described in #6915 *except* that we care about the loadedRegion windows of *all* past successful analysis runs for that location, not just the most recent successful run.

A subtask of https://github.com/RecordReplay/devtools/issues/6591

---

PREVIOUS CONTEXT FOR POSTERITY

- This is probably not going to be *that* common of a requirement, because, for example, if an analysis gets run *once* at the findPoints level, we will know the correct points for the entire recording and every possible focus region of the recording, and if the analysis has run successfully, we will also know the evaluation at those points, so we will not need to requery until the user changes the expression)
  - A note about points vs location: right now we always run analyses by adding the location of the print statement, but we *could* add a subset of points when we know there will be too many to run a full analysis. This is not a top priority, but it will be a requirement for whatever comes out of https://github.com/RecordReplay/design/issues/36 and should be the kind of operation that our changes will support in the future.
- (In a lot of ways, this is going to line up with other work that we're doing under the umbrella of #6590 , because the loading and focus transitions that would cause analyses to re-run, will also trigger other data refetching)

**Comment by jaril** [comment]
@jcmorrow add detail :pray:

**Comment by gideonred** [comment]
This ticket has been moved to [FE-190](https://linear.app/replay/issue/FE-190/rerun-analyses-upon-some-focusloaded-region-changes)
