### ISSUE TITLE
Restructuring the state management for running analyses

### ISSUE THREAD

**Issue by jcmorrow** [replayio/devtools#6853]
See https://github.com/RecordReplay/devtools/issues/6591 for a *lot* more context

While analyses are in the process of being run (either finding their points [`findPoints` or generating results [`runAnalysis`]), what are we recording about the process so far, the status, maybe even partial results (because things do not get emitted all at once), and how can the UI layer pull out that information to show the right thing to the user?

**Comment by jaril** [comment]
@markerikson to close?

**Comment by markerikson** [comment]
The state management part was completed in #6980 , and used in #7051 .
