### ISSUE TITLE
Show replay title in tab

### ISSUE THREAD

**Issue by jasonLaster** [replayio/devtools#6862]
**Description:**
We should add the replay title as a `<title>`
<img width="913" alt="Screen Shot 2022-05-19 at 9 32 56 AM" src="https://user-images.githubusercontent.com/254562/169429989-b50e6df6-5f97-40e3-81ec-b68db1058534.png">

**Comment by jonbell-lot23** [comment]
Agree -- and it's alway my preference to be user centric with the title. Meaning:

[Our logo] Climatescape saf shows up twice
is better than
[Our logo] Replay: Climatescape saf shows up twice

Especially when tabs get tight. You'd rather see
[Our logo] Climat...
than
[Our logo] Replay...
