### ISSUE TITLE
Plus button UI polish

### ISSUE THREAD

**Issue by jasonLaster** [replayio/devtools#6866]
- [ ] There should be a small gap between the line number tooltip and the plus button
- [ ] Hovering on the plus button should not show the breakpoint badge
- [ ] tooltip is clipped
- [ ] minus badge should hide when moused off of the panel

https://app.replay.io/recording/plus-button--10fca3c0-8792-434b-940e-993efc083969?point=53221042808195801819626386841669435&time=18752.336099585063&hasFrames=false

### Badge
<img width="162" alt="Screen Shot 2022-05-19 at 9 56 22 PM" src="https://user-images.githubusercontent.com/254562/169453458-9d2d3454-0481-4346-8da5-b2614de3ea8a.png">

### Tooltip clipped
<img width="1134" alt="Screen Shot 2022-05-19 at 10 04 32 PM" src="https://user-images.githubusercontent.com/254562/169454278-4a92e692-b195-4b4a-8bd3-07768e6209e9.png">

**Comment by gideonred** [comment]
This ticket has been moved to [FE-194](https://linear.app/replay/issue/FE-194/plus-button-ui-polish)
