### ISSUE TITLE
Trying to log an undefined value to the console breaks the hit count

### ISSUE THREAD

**Issue by ceceliacreates** [replayio/devtools#6872]
**Description:**
Trying to log an undefined value to the console breaks the hit count.

**Steps to Reproduce:**
See replay, not sure if applies in all cases, but in this case:

- initial line hit count was 228
- added a print statement and logged a value to the console that should have returned `undefined`
- Console stuck at "Loading"
- Print statement panel prompted me to use Focus Mode because of 10k+ hits
- After removing the print statement, line hover showed 10k+ hits

**Expected Result:**

**Additional Context:**

* Screenshots:
* Video (Loom):
* Replay ([replay.io/record-bugs](https://replay.io/record-bugs) for instructions):

https://app.replay.io/recording/replay-trying-to-log-undefined-value-breaks-hit-count--1134a408-9ccf-441c-b3ca-59e26108697f

**Comment by jcmorrow** [comment]
Yeah this is one of many of this type of bug that will be solved by #6591

**Comment by jcmorrow** [comment]
I don't think we should spend time trying to pile on even more workarounds for this type of thing. The code is already a house of cards, and it's hard to fix one edge case without breaking another, so I think any effort should be spent supporting @markerikson on getting the new analysis management across the finish line.

**Comment by jcmorrow** [comment]
This is fixed
