### ISSUE TITLE
Right-click on gutter should alway show "add comment" context menu

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/devtools#6911]
Today you can right-click on a gutter with no hits to add a comment, but if you right-click on a part of the gutter with hits, nothing happens. (First spotted here: https://www.loom.com/share/982c007dc08642d79085d0a7a7e4b539?t=32)

Both should have the same context menu.

**Comment by jonbell-lot23** [comment]
cc @jaril Good "broken window" that should be easy to knock out and would be good to address

**Comment by gideonred** [comment]
This ticket has been moved to [FE-195](https://linear.app/replay/issue/FE-195/right-click-on-gutter-should-alway-show-add-comment-context-menu)
