### ISSUE TITLE
Global Loader 1.6

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/devtools#6913]
Global Loader 1.5 is a big step forward, and here are some small revisions we've discussed for 1.6

**Ready to be discussed + worked on:**

- [x] #6849
- [x] #7064 ([design-discussion](https://github.com/RecordReplay/design/issues/65))
- [x] #7053 ([design-discussion](https://github.com/RecordReplay/design/issues/65))
- [x] #7060 ([design-discussion](https://github.com/RecordReplay/design/issues/64))

<details>
  <summary>Old stuff no longer in scope</summary>
  
Other:
- [ ] ~~Buffer information when you hover on the play button ([design-discussion](https://github.com/RecordReplay/design/issues/66))~~
    * ~~Also hovering over the timeline -- buffering versus processing (Jon recommends holding off on this)~~
- [ ] ~~Make sure we're only using the term "video only" rather than "unloaded" in the UI (might be redundant)~~
- [ ] ~~Add context menu to the timeline (not recommended yet)~~
</details>

**Comment by bvaughn** [comment]
> Cursor shouldn't be a text input cursor on timestamp (keep standard pointer)

Just to clarify here, the text cursor _is_ actually the standard cursor for browsers like Safari (which I believe you use) when hovering over text like our timestamp. We can override it by using CSS to disable text selection (`user-select: none`) or we could override the cursor itself (`cursor: default`) if you'd like to though. 😄

**Comment by jonbell-lot23** [comment]
> > * [ ]  Cursor shouldn't be a text input cursor on timestamp (keep standard pointer)
> 
> Just to clarify here, the text cursor _is_ actually the standard cursor for browsers like Safari (which I believe you use) when hovering over text like our timestamp. We can override it by using CSS to disable text selection (`user-select: none`) or we could override the cursor itself (`cursor: default`) if you'd like to though. 😄

Makes sense. Yup, that's what would be best, thanks! (And then of course when the precision editor is up, we'd use the text input cursor again)

**Comment by jonbell-lot23** [comment]
Update: each of these design items have a POV attached. See links above for Loom walkthroughs and screenshots.

**Comment by bvaughn** [comment]
@jonbell-lot23 What does "Surface unloaded data" mean?

Sorry if we've talked about this and I've just forgotten, but I'm not sure what that means in terms of actionable work.

**Comment by jonbell-lot23** [comment]
You are right to be confused! That was a bite I forgot to flesh out.

It came from a backend discussion like "wait, do we have this data to show in the UI?" Sounds like we do? To discuss.

**Comment by jaril** [comment]
Surface unloaded data: Whenever you constrict the focus area such that things are "lost", maybe point out to the user that those things have been blown away.

**Comment by bvaughn** [comment]
IMO "whenever we've trimmed something, let the user know we trimmed it" seems too broad to be actionable.

"show a message above and below console logs when we've filtered some out" seems really actionable though

**Comment by jaril** [comment]
> "show a message above and below console logs when we've filtered some out" seems really actionable though

Yep! I think at the very least, an acknowledgement that you've focused and so there may be logs before and/or after what's displayed, is useful. That way the user is not misled to thinking that what's shown is all there is.

A bonus would be if we could have some number attached to it ("there are n number of logs after this part but you can't see them because of your focus region"). But I'm not super confident that we can get that number easily.

**Comment by markerikson** [comment]
@jaril We... _could_ without too much difficulty, I think.

Right now we keep the list of visible message IDs in `state.messages.visibleMessages`, calculated in the reducer.

At a minimum, you can do trivial math to compare the length of that array vs the total number of messages in the table, and say "N messages hidden".

If we want to do the before/after comparison, we _ought_ to be able to write a couple selectors that pull out that data.  I don't see any blockers here - just gotta write the code that does the filtering.

**Comment by bvaughn** [comment]
> IMO "whenever we've trimmed something, let the user know we trimmed it" seems too broad to be actionable.
> "show a message above and below console logs when we've filtered some out" seems really actionable though

Had a thought about this and wanted to leave it here while it was fresh.

The only case when we can show the number of filtered logs will be for recordings that _don't overflow at all_. If we overflow at all (without a focus region) then we won't be able to reliably to tell users how many messages are _outside of_ their focus region (at least not without a backend update to calculate and send this info).

This is probably understood. I just wanted to make sure we were on the same page.

**Comment by bvaughn** [comment]
> - [ ] Don't stop video playback when you reach the end of a focus window

The design issue that this bullet links to (https://github.com/replayio/design/issues/65) has more scope than the little bullet point. In fact, it looks to be _primarily_ about showing the number of logs we filtered before/after the focus region, so the scope of this issue is kind of ambiguous.

**Comment by bvaughn** [comment]
Removing the sync-video feature flag (#7062) seems to greatly reduce the complexity of enabling the new "play video outside of the focus region" behavior.
