### ISSUE TITLE
Failing test: breakpoints-07

### ISSUE THREAD

**Issue by jaril** [replayio/devtools#6919]
Replay: https://app.replay.io/recording/replay-of-devtools-m3yk8crmh-recordreplayvercelapp--258d37cf-db69-43b9-91fa-202c99f2be1b

There seems to be a spike of breakpoint-07 test failures ([see here](https://ui.honeycomb.io/replay/datasets/backend/result/Hp3Ese95Vtv/a/3fveKN7U4W1?useStackedGraphs)). @hbenl I think you might have been looking at this already — can you let me know in case you've made more progress on it than I have?

**Comment by hbenl** [comment]
I did look at it briefly and noticed that the backend responds with an internal error to the `Debugger.setBreakpoint` commands, so this is probably a backend issue.

**Comment by jaril** [comment]
https://github.com/RecordReplay/backend/pull/5727 has been merged but it looks like the most recent breakpoints-07 test runs are still failing.

**Comment by jaril** [comment]
Linking most recent issue: https://github.com/RecordReplay/backend/issues/5736.

**Comment by jaril** [comment]
It looks like this has stopped becoming a problem as of last night, not seeing instances of the same error popping up in honeycomb anymore.

https://ui.honeycomb.io/replay/datasets/backend/result/ENB5fBCveDb/a/3fveKN7U4W1?useStackedGraphs

Will check again later today and if that's still the case, will be closing it.

**Comment by jaril** [comment]
Not seeing this _as often_, but keeping it open to keep an eye on it.

**Comment by jaril** [comment]
This is happening again: https://ui.honeycomb.io/replay/datasets/backend/result/4nSpxnJbYHr/a/3fveKN7U4W1?useStackedGraphs

**Comment by hbenl** [comment]
Here's the recording of a recent failure: https://app.replay.io/recording/be410907-4775-4864-9d9d-343e21d7a2f4
There's a logpoint with 2 hits but only one corresponding console message:
![Screenshot from 2022-06-07 16-17-22](https://user-images.githubusercontent.com/16060807/172403775-850d8dc9-bc82-4141-8655-996cd3f50c1e.png)
![Screenshot from 2022-06-07 16-19-42](https://user-images.githubusercontent.com/16060807/172403981-15d20738-0cc3-4463-94e9-5ce8dbd5e83e.png)
