### ISSUE TITLE
There's no way to navigate back to the paused position in the console when it's off-window

### ISSUE THREAD

**Issue by jaril** [replayio/devtools#6921]
This was generated from antidnan's [post on Discord](https://discord.com/channels/779097926135054346/912494011464421436/978378926776787004):

```
I've been dealing with a bunch of long logs in the replay console these past few days and I keep getting lost in the scrolling. I wish there was a button that scrolled the console back to the timestamp that the replay is paused at (the red line in the console). Is there a way to do this now?
```

**Comment by jaril** [comment]
This is an often-enough occurrence that, even though it's UI polish, is probably worth adding to improve the debugging experience when it's at its worst (long logs in the console). Assigning it to the next sprint to be picked up then.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-196](https://linear.app/replay/issue/FE-196/theres-no-way-to-navigate-back-to-the-paused-position-in-the-console)
