### ISSUE TITLE
:bug: on DevTools: enabling 'messages' in console doesn't...

### ISSUE THREAD

**Issue by jperl** [replayio/devtools#6939]
:bug: on DevTools: enabling 'messages' in console doesn't make messages viewable, errors in console

steps to repro:
• log in 
• view replay's Devtools tab
• enable worker &gt; message
• no message viewable, errors in console
affected test:
<https://app.qawolf.com/test/ckz327u1u114841951p43t4ace73|Hide node modules with user role> \- [Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1653433554740239)

**Comment by jaril** [comment]
Events seem to be finicky. THere was a similar error that was resolved by adding a longer time out. 

https://github.com/RecordReplay/devtools/issues/6652

This needs more investigation.
