### ISSUE TITLE
Add some indication when the user has an unapplied, pending filter string and they've focused away from the search box

### ISSUE THREAD

**Issue by jcmorrow** [replayio/devtools#6947]
https://app.replay.io/recording/filtering-is-broken--0e624a72-3404-472a-a551-b1ca47a52294?point=51273931526959079127049417261064264&time=27900&hasFrames=false

**Comment by jcmorrow** [comment]
@jaril not sure what's going on here, but it seems up your alley!

**Comment by jcmorrow** [comment]
Also, this is a bit of a side issue, but I find it very counterintuitive that when you delete the search term from the bar, it does not clear the filter. You have to hit "enter" again to get your recordings to show up. I don't know if it makes more sense to reload them on change or on blur, but it seems like we should probably do one of those.

**Comment by jaril** [comment]
Got a fix in over in backend! https://github.com/RecordReplay/backend/pull/5742

> Also, this is a bit of a side issue, but I find it very counterintuitive that when you delete the search term from the bar, it does not clear the filter. You have to hit "enter" again to get your recordings to show up. I don't know if it makes more sense to reload them on change or on blur, but it seems like we should probably do one of those.

Yeah @bvaughn also brought this up. That implementation was lifted from GitHub's filter bar but I think I'm in the same boat — not a fan of the possibility that the user might mistakenly think that a filter's applied when it's not. Keeping this issue open until that part's resolved.

**Comment by jaril** [comment]
Fix is merged so filtering is fixed — @jcmorrow mind double checking on your side?

Keeping this open until we have some way of being more explicit about pending changes to the filter.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-197](https://linear.app/replay/issue/FE-197/add-some-indication-when-the-user-has-an-unapplied-pending-filter)
