### ISSUE TITLE
Should be easy to collapse exceptions

### ISSUE THREAD

**Issue by jasonLaster** [replayio/devtools#6972]
> The other thing I noticed was it was hard/impossible to collapse a verbose exception. It made our console.logs cluttered.

![image](https://user-images.githubusercontent.com/254562/170527792-d62669ec-2b79-47bc-bd70-46ff08a69bdd.png)

**Comment by gideonred** [comment]
This ticket has been moved to [FE-198](https://linear.app/replay/issue/FE-198/should-be-easy-to-collapse-exceptions)
