### ISSUE TITLE
The file picker should be faster

### ISSUE THREAD

**Issue by jcmorrow** [replayio/devtools#6975]
I have no technical definition for "too slow" here, but it's *definitely* too slow. Recording performance has been pretty terrible for me lately, but trust me, even when not recording, it takes a long time to find the file, even after it is *clear* that sources have loaded (because they are in the sidebar). I understand that sometimes there are a lot of files, but it seems very likely that we could stream results back rather than having this be an all or nothing affair. This would be especially nice because we could prioritize searching folders that are not in `node_modules` and we would likely return the file that the user is looking for much, much faster.

https://app.replay.io/recording/finding-a-file-is-so-slow--44f6312e-8fc3-47a2-ad09-4c172ae1e191

**Comment by gideonred** [comment]
This ticket has been moved to [FE-199](https://linear.app/replay/issue/FE-199/the-file-picker-should-be-faster)
