### ISSUE TITLE
:bug: on DevTools: Unable to bulk move items back to 'You...

### ISSUE THREAD

**Issue by jperl** [replayio/devtools#6995]
:bug: on DevTools: Unable to bulk move items back to 'Your Library'
• Log in and bulk move items to another team
• Bulk select items &amp; attempt to move back to 'Your Library'
Expected: Able to move items
Result: "Move to:" not an option in the actions menu
Affected test: [Library: Bulk edit from library](https://app.qawolf.com/test/cl2kkz4i5121151dqwfpkm9aoz)

[Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1653925897929579)

**Comment by jaril** [comment]
Trying to resolve this test behavior in the slack channel: https://replayio.slack.com/archives/C02GEJCC9JP/p1653925897929579

**Comment by gideonred** [comment]
This ticket has been moved to [FE-200](https://linear.app/replay/issue/FE-200/bug-on-devtools-unable-to-bulk-move-items-back-to-you)
