### ISSUE TITLE
Completions suggesting numbers should insert indexed access

### ISSUE THREAD

**Issue by Andarist** [replayio/devtools#6997]
**Description:**

A raw number is inserted when selecting an available index from the completions popup~. This results in an invalid expression in the console's input.

**Steps to Reproduce:**

1. find an array and check its properties
<img width="299" alt="Screenshot 2022-05-31 at 08 59 09" src="https://user-images.githubusercontent.com/9800850/171111682-72176d80-a445-49ef-a619-c83b4d11f848.png">
2. select an index
<img width="127" alt="Screenshot 2022-05-31 at 08 59 36" src="https://user-images.githubusercontent.com/9800850/171111795-26a54bb6-a823-4246-8201-d055a69a86f3.png">
3. try to evaluate the resulting expression
<img width="262" alt="Screenshot 2022-05-31 at 09 00 13" src="https://user-images.githubusercontent.com/9800850/171111876-85115686-64d5-43ed-a85e-4955cb7526d1.png">

**Expected Result:**

`[0]` should be inserted

**Additional context**

I'm using node recorder

**Comment by gideonred** [comment]
This ticket has been moved to [FE-201](https://linear.app/replay/issue/FE-201/completions-suggesting-numbers-should-insert-indexed-access)
