### ISSUE TITLE
Apollo error upon moving a replay in the library

### ISSUE THREAD

**Issue by jcmorrow** [replayio/devtools#7002]
Replay: https://app.replay.io/recording/apollo-error-when-moving-replay--11636909-1aab-423b-bd64-569686077a16?point=32451855388208111629992485638375290&time=14512&hasFrames=true#

This still *works*, but Apollo cache errors. It's not a huge deal, but Apollo cache errors are the kind of thing that are easy to ignore until they introduce a subtle bug that later becomes very hard to track down.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-202](https://linear.app/replay/issue/FE-202/apollo-error-upon-moving-a-replay-in-the-library)
