### ISSUE TITLE
Users stuck on Onboarding "Let's time travel screen" for a long time with no indication of anything loading

### ISSUE THREAD

**Issue by gideonred** [replayio/devtools#7030]
Kannan and I were looking into sessions that had a long loading time. One theme came up when looking at log rocket. In almost every case the person was stuck at the "Let's time travel" screen, and after clicking "Ready as I'll ever be, doc", nothing happens. We eventually load in. As far as we can see there's no loading screen shown.

Logrocket sessions: https://app.logrocket.com/4sdo4i/replay/s/5-561a6b7f-69c4-4106-8893-7269c03c26c5/0?dashboardID=logrocket-overview&filters=%255B%257B%2522id%2522%253A%2522Sk-SnxHuq%2522%252C%2522type%2522%253A%2522email%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522is%2522%252C%2522type%2522%253A%2522IS%2522%252C%2522hasStrings%2522%253Atrue%252C%2522autocompleteEnabled%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522mohamed%2540brevy.com%2522%255D%257D%255D&fromTab=metrics&log_filter=session&t=1654039965161.0454

https://app.logrocket.com/4sdo4i/replay/s/5-f9f90ffe-7fbf-4575-8a6e-8e52b76956a3/0?dashboardID=logrocket-overview&filters=%255B%257B%2522id%2522%253A%2522rknAqeSd9%2522%252C%2522type%2522%253A%2522email%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522is%2522%252C%2522type%2522%253A%2522IS%2522%252C%2522hasStrings%2522%253Atrue%252C%2522autocompleteEnabled%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522darian%2540vinnauto.com%2522%255D%257D%255D&fromTab=metrics&t=1654021888850.943

https://app.logrocket.com/4sdo4i/replay/s/5-ad101c0b-b656-4dbb-9ce7-0e3976358ead/0?dashboardID=logrocket-overview&filters=%255B%257B%2522id%2522%253A%2522SkUnpxSO9%2522%252C%2522type%2522%253A%2522email%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522is%2522%252C%2522type%2522%253A%2522IS%2522%252C%2522hasStrings%2522%253Atrue%252C%2522autocompleteEnabled%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522dong.linlan%2540gmail.com%2522%255D%257D%255D&fromTab=metrics&t=1653896316738.217

**Comment by jonbell-lot23** [comment]
Great point @jaril and @gideonred .

Yeah, we target a new tab here, so that's what's going wrong. I don't have my data in front of me because it's Saturday but I believe this feels broken in the current flow. (For UX reasons, not logrocket ones)

So I think the "ready as I'll ever be" page should stay on the same tab unless we can explain why that somehow breaks something. Then we fix our logrocket and UX issues at the same time.

**Comment by jaril** [comment]
> Thanks for the insight. What's weird though is that the metric @jaril introduced is showing that these people are having very long loading times. I'll look closer at could be happening here.
> 
> For now, the original issue I filed for is not an issue.

AHH that's how this got surfaced. Yeah I think that's right. Closign this for now!
