### ISSUE TITLE
Use points to run analyses inside of a given focus window

### ISSUE THREAD

**Issue by jcmorrow** [replayio/devtools#7036]
This is a specific subset of where https://github.com/RecordReplay/design/issues/36 meets https://github.com/RecordReplay/devtools/issues/6591.

When we are running an analysis for a log point we should:

- If we do not yet know the points for that location in our focus window, run `Analysis.findPoints`
- Once we know the points, create an analysis, add those points to it, and run that analysis

This is in contrast to always running on a particular location.

**Comment by jaril** [comment]
Same as shttps://github.com/replayio/devtools/issues/7032, setting this for this current sprint. Let me know if that's not correct!

**Comment by jcmorrow** [comment]
This was actually done in #7055 🎉

**Comment by gideonred** [comment]
This ticket has been moved to [FE-106](https://linear.app/replay/issue/FE-106/use-points-to-run-analyses-inside-of-a-given-focus-window)
