### ISSUE TITLE
"Large Text" setting results in offset location for line hover button

### ISSUE THREAD

**Issue by markerikson** [replayio/devtools#7038]
When the experimental "Large Text" setting is enabled, hovering over a line number results in the blue "+" button showing up one line too low.

/cc @ryota-murakami if you're interested in checking this

**Comment by ryota-murakami** [comment]
@markerikson Thanks reporting this, I can work at weekend about it:)

**Comment by ryota-murakami** [comment]
@markerikson Would you mind attach screenshots or short video?
I'd like to know where is that happening exactly.

**Comment by jaril** [comment]
> @markerikson Would you mind attach screenshots or short video? I'd like to know where is that happening exactly.

@ryota-murakami Jumped in to record this one since I was around the vicinity anyway! https://www.loom.com/share/fed9a5c018c440c594aed9313fc03bd9

**Comment by ryota-murakami** [comment]
THis is realy for review.
https://github.com/replayio/devtools/pull/7072

**Comment by markerikson** [comment]
@ryota-murakami Yeah, totally understand.  I did just merge the hover tooltip fix PR.  

Really hope you can get things figured out soon!

**Comment by gideonred** [comment]
This ticket has been moved to [FE-107](https://linear.app/replay/issue/FE-107/large-text-setting-results-in-offset-location-for-line-hover-button)
