### ISSUE TITLE
:bug: on DevTools: Receiving less than 1000+ console mess...

### ISSUE THREAD

**Issue by jperl** [replayio/devtools#7042]
:bug: on DevTools: Receiving less than 1000+ console messages and dummyValue is not defined error
Steps to recreate:
• Log in to Replay
• Go to 1000 hits replay ([Assert console error on Replays with 1000+ console messages](https://staging.app.replay.io/recording/1000-hits--76ff5bc7-fcf7-459b-a711-86b1df46a6f4>)
• Hover over the while loop and click the + for dropdown.
• View 10k+ hits but 979 console messages in built in console
Expected: 1001 hits
Results: 10k+ hits and 979 console messages,  dummyValue is not defined error.

Affected tests: <https://app.qawolf.com/test/ckz7kni7y16626152qqker2w2a2?suite_id=cl3vzghtc34446553oqcvddbszj)

[Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1654130211443529)

**Comment by jaril** [comment]
This is passing. Waiting for confirmation before closing.

![Uploading image.png…]()


https://replayio.slack.com/archives/C02GEJCC9JP/p1654130211443529

**Comment by jcmorrow** [comment]
I'm gonna close this since we released a fix for these issues last week. If we're still seeing, I expect QAWolf would open an new ticket.
