### ISSUE TITLE
:bug: on DevTools: Over 10k+ hits when expected to see 45...

### ISSUE THREAD

**Issue by jperl** [replayio/devtools#7043]
:bug: on DevTools: Over 10k+ hits when expected to see 4501
Steps to recreate:
• Log in to Replay
• Go to 1000 hits replay ([Breakpoint panel 500+ hits warning](https://staging.app.replay.io/recording/hello-world-45k-loop--a78bb419-e36b-42bf-a918-b43385a5fb2a>)
• Hover over the while loop and click the + for dropdown.
Expected: 4501 hits
Results: 10k+ hits and dummyValue is not defined error.

Affected tests: <https://app.qawolf.com/test/ckyf2ajm8000009maadns2p5w?suite_id=cl3vzghtc34446553oqcvddbszj)

Link to replay is attached below:
[https://app.replay.io/recording/breakpoint-panel-500-hits-warning-replay-daily-repl[…]53545561364647550979122608459481088&amp;time=21415&amp;hasFrames=false](https://app.replay.io/recording/breakpoint-panel-500-hits-warning-replay-daily-replay-qa-wolf--52859843-9183-4c5c-b599-0996b4234777?point=53545561364647550979122608459481088&amp;time=21415&amp;hasFrames=false)

Screenshot of expected behaviour below.

[Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1654130410271679)

**Comment by jcmorrow** [comment]
This will be closed soon as part of fixing up error handling for analyses 👌

**Comment by jaril** [comment]
Just reran the tests and it seems to be working fine now. Will bring it up in Slack.

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/15959269/171776440-90565bee-97ef-475f-b116-91b1926d5881.png">

https://replayio.slack.com/archives/C02GEJCC9JP/p1654130410271679 @jcmorrow for visibility 🙋‍♂️

**Comment by jcmorrow** [comment]
I am pretty sure we confirmed with QAWolf that this is fixed.
