### ISSUE TITLE
Polish DevTools for landing page

### ISSUE THREAD

**Issue by souporserious** [replayio/devtools#7046]
- [ ] Print Statement: Refresh editing flow
- [x] Print Statement: Unicorn picker
- [x] Network Monitor: Filter drawer
- [ ] Network Monitor: Stack trace
- [ ] React DevTools: Add comment
- [ ] React DevTools: Component timeline

**Comment by gideonred** [comment]
This ticket has been moved to [FE-206](https://linear.app/replay/issue/FE-206/polish-devtools-for-landing-page)
