### ISSUE TITLE
Long console error messages are cut off.

### ISSUE THREAD

**Issue by jazzdan** [replayio/devtools#7048]
**Description:**
If there is an error in the console that is sufficiently long it can be really hard to see the entire error. The error gets cut off, doesn't over flow and sometimes you can't make the pane big enough to see all of it.

**Steps to Reproduce:**
See this replay https://app.replay.io/recording/replay-cant-see-entire-console-error-message--c6915955-eb31-49d3-adb4-ec3849edc306

**Expected Result:**
I would have expected long console errors to line wrap or be horizontally scrollable.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-208](https://linear.app/replay/issue/FE-208/long-console-error-messages-are-cut-off)
