### ISSUE TITLE
Sometimes E2E test failures time out when they could fail fast

### ISSUE THREAD

**Issue by jcmorrow** [replayio/devtools#7049]
Here's one example with a comment:

https://app.replay.io/recording/replay-of-devtools-87h4loy1y-recordreplayvercelapp--34b7c108-1f2e-43ab-83f5-f1583ac34a8a?point=57439784001104008514229074703420950&time=27680&hasFrames=true

**Comment by gideonred** [comment]
This ticket has been moved to [FE-209](https://linear.app/replay/issue/FE-209/sometimes-e2e-test-failures-time-out-when-they-could-fail-fast)
