### ISSUE TITLE
:bug: on DevTools: clicking fast forward button in consol...

### ISSUE THREAD

**Issue by jperl** [replayio/devtools#7054]
:bug: on DevTools: clicking fast forward button in console errors out to blank page

steps to repro:
• open a replay
• open replay's devtools
• click fast-forward on an item in console
• blank page, errors in console (Command error and Range error)
replay:
[Add and delete comment from console](https://app.replay.io/recording/clicking-fast-forward-errors-out-with-blank-page--6e4f42eb-d8c5-40a0-bc87-a07308201635>

affected test:
<https://app.qawolf.com/test/ckyx7laak92221350mirjnmkb4d)

[Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1654209000691899)

**Comment by jcmorrow** [comment]
I suspect that https://github.com/replayio/devtools/issues/7058 has fixed this.

**Comment by gideonred** [comment]
I tried rerunning the test (https://app.qawolf.com/test/ckyx7laak92221350mirjnmkb4d), but it's running into invalid recording Id.

**Comment by jaril** [comment]
Followed up with them: https://replayio.slack.com/archives/C02GEJCC9JP/p1654209000691899

**Comment by gideonred** [comment]
This ticket has been moved to [FE-210](https://linear.app/replay/issue/FE-210/bug-on-devtools-clicking-fast-forward-button-in-consol)
