### ISSUE TITLE
Session.createPause failure crashes devtools

### ISSUE THREAD

**Issue by hbenl** [replayio/devtools#7058]
#7009 triggered a bug in the Message component: when there is no current point (which happens when Session.createPause fails), it uses a default value of `Number.POSITIVE_INFINITY`, but that can't be converted to a BigInt.
https://app.replay.io/recording/replay-crash--5fbf3aff-802b-4617-b961-6babba24548a

**Comment by hbenl** [comment]
I fixed the crash in #7059 but wanted to call out that we need to start thinking about how to handle situations where there is no current pause. There are probably a lot of places in devtools that assume that there always is a current pause (at least after calling `ThreadFront.ensureCurrentPause()`) but if we want to handle `Session.createPause` failures correctly (and if we want to allow the user to jump to points outside the current focus region), we need to remove that assumption.
@jcmorrow @bvaughn

**Comment by jcmorrow** [comment]
>  There are probably a lot of places in devtools that assume that there always is a current pause

Agreed, this is not ideal.
