### ISSUE TITLE
Audit code for consistent use of "begin" and "end"

### ISSUE THREAD

**Issue by bvaughn** [replayio/devtools#7065]
Right now the frontend uses a mix of the terms "begin" and "end" (which matches the backend protocol) and "start" and "end". We should remove the latter for consistency (and because it's kind of semantically goofy too).

**Comment by codingnninja** [comment]
@bvaughn I will take this up to get started with the code base.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-211](https://linear.app/replay/issue/FE-211/audit-code-for-consistent-use-of-begin-and-end)
