### ISSUE TITLE
Messed up comment locations

### ISSUE THREAD

**Issue by bhackett1024** [replayio/devtools#7067]
Spun off from https://github.com/replayio/backend/issues/5863.  Replay: https://app.replay.io/recording/bad-comments--b5f6b34f-0240-4c59-af3d-cd212435b7ad?point=54194598486288670140805861521492907&time=22516.449554896142&hasFrames=false

**Comment by jcmorrow** [comment]
Pretty sure this was just miscommunication on my part. Those were the correct locations for those comments, and they did not have pause points because the thing I was commenting on was my inability to get hitcounts/points to seek to for leaving comments on 🤷
