### ISSUE TITLE
Cancel or delete a draft comment

### ISSUE THREAD

**Issue by ceceliacreates** [replayio/devtools#7073]
**Description:**
Currently, if you create a comment accidentally or decide you don't want to create a comment after all, there is not a clear way to cancel or delete the draft comment. You have to refresh to remove the comment draft box.

**Steps to Reproduce:**
Create a comment. Try to delete without saving.

**Expected Result:**
Comment would have "Cancel" or "Delete" option when in draft mode.

**Additional Context:**

* Screenshots:
* Video (Loom):
* Replay ([replay.io/record-bugs](https://replay.io/record-bugs) for instructions):

https://app.replay.io/recording/replay-cant-delete-draft-comment--d77d2a9f-d45f-4887-9a79-3ad107dd9773

**Comment by gideonred** [comment]
This ticket has been moved to [FE-213](https://linear.app/replay/issue/FE-213/cancel-or-delete-a-draft-comment)
