### ISSUE TITLE
Filters are broken in library 

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/devtools#7075]
Loom: https://www.loom.com/share/5166b9f350254cb286155e0a64eef243
Replay: https://app.replay.io/recording/filters-broken-in-library--7806ed02-9eaf-4ea4-8a7a-61e7f89cf796

When I select "Last 7 days" or the other filters, nothing happens.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-214](https://linear.app/replay/issue/FE-214/filters-are-broken-in-library)
