### ISSUE TITLE
Logging out of app.replay.io redirects me http://localhost:3000/

### ISSUE THREAD

**Issue by gideonred** [replayio/devtools#7076]
After logging into app.replay.io (production), if I log out, I'm redirected to http://localhost:3000/.

I don't expect the production site to be redirecting me to anything localhost.

I wish I could make a Replay, but the act of logging out causes the Replay to stop.

Old school recording:

https://user-images.githubusercontent.com/28845582/172190212-ef1bbab7-8ded-4b6d-a687-b648f2d4b25f.mov

**Comment by jaril** [comment]
Duplicate in: https://github.com/replayio/devtools/issues/7076
