### ISSUE TITLE
Handling disconnect messaging

### ISSUE THREAD

**Issue by jcmorrow** [replayio/devtools#7077]
We now raise a `session was destroyed` style error when a controller dies due to not being used for a while. Before that we get a series of warning which we also don't handle right now.

```
sessionId: "f5ea099a-21d9-4a8c-b19a-2f87f9941aae/87b438d0-562b-4bb8-afc6-671b4a457495"
Received unknown message method: "Session.mayDestroy"params: {time: {…}}, sessionId: "f5ea099a-21d9-4a8c-b19a-
Message failed Session.listenForLoadChanges, code: 66, id: 8, message: "The session was destroyed while the command was in progress", undefined
Received unknown message method: "Connection.mayDisconnect"params: {time: {…}}
```

Probably we should:

- Store the warnings in the store (eventually it would be nice to maybe pop a modal telling the user we will disconnect soon and letting them cancel that, but we don't need to do that now)
- If we have that warning in the store, and we get a `sessionDestroyed` we should consider that an "expected" error

**Comment by gideonred** [comment]
Related https://github.com/replayio/devtools/issues/7003

**Comment by jcmorrow** [comment]
Oh thanks @gideonred , I was looking for an equivalent card and did not see it, I'll close this one
