### ISSUE TITLE
Devtools reporting "we'll look into it as soon as possible." when we wont.

### ISSUE THREAD

**Issue by gideonred** [replayio/devtools#7079]
This may be covered by https://github.com/replayio/devtools/issues/7003, but I wanted to cut a separate ticket because there might be a shorter term solution.

The backend can now close sessions due to inactivity, here's an example of a session being closed:

https://ui.honeycomb.io/replay/datasets/backend/result/gP8qJTHPPdR

When this happens, devtools reports "Something went wrong while replaying, we'll look into it as soon as possible.". Neither of those statements are correct in this case:

https://ui.honeycomb.io/replay/datasets/backend/result/As2FChqojbr

It is new behavior for the backend to close a session with this message, and I believe devtools doesn't support it yet: https://github.com/replayio/backend/blob/master/src/channel/dispatcher-controller.ts#L87

cc @loganfsmyth

**Comment by jcmorrow** [comment]
Yeah I agree. We're doing a lot of rethinking of how we handle things, which is fine, but the first goal should be avoiding regressions. I'll take a quick swing at this now, shouldn't be too complicated without any other changes.
