### ISSUE TITLE
Focus Window edge cases

### ISSUE THREAD

**Issue by jasonLaster** [replayio/devtools#7090]
Saw two edge cases in this [replay](https://app.replay.io/recording/focus-window-console-messages--d2886ce7-bc4a-4d45-9ed6-7d94556f0372?point=96706529039814627722125151026806784&time=35368.20751761942&hasFrames=false)
1. we say there are too many messages, but dont show any messages in the console
2. the focus window is set to the end, but we say there might be messages after the window

**Comment by bvaughn** [comment]
Happy to look at this but at least for the moment it's not in the current sprint– so I assume it should not be prioritized over other things.

**Comment by bvaughn** [comment]
From what I can see, I think #7101 is the only "fix" here.

However I think we should probably probably also make a UX tweak:
> Perhaps we could change the wording in this case to say something more like "_There are at least X messages outside of your debugging window_"

**Comment by bvaughn** [comment]
#7102 is an optional messaging tweak that _I think_ is a small improvement to the edge case I described above.
