### ISSUE TITLE
Network Monitor Stack Trace panel never loads

### ISSUE THREAD

**Issue by souporserious** [replayio/devtools#7094]
**Description:**
The Stack Trace panel never loads.

**Steps to Reproduce:**
Navigate to a POST request in the Network Monitor and view the Stack Trace panel which never seems to load.

**Expected Result:**
It shows the correct Stack Trace at the time of the POST.

https://app.replay.io/recording/network-monitor-stack-trace-never-loads--53f4da67-69bc-48cc-b0b3-a02d22dc5b5c

**Comment by jcmorrow** [comment]
@souporserious could you make the original Replay public? That might help with diagnosing

**Comment by souporserious** [comment]
Ah, yes! Here it is https://app.replay.io/recording/overboard--e5575afa-4719-4df8-ae45-d0639ae46b15
