### ISSUE TITLE
:bug: on DevTools: Focus region not constraining playback...

### ISSUE THREAD

**Issue by jperl** [replayio/devtools#7104]
:bug: on DevTools: Focus region not constraining playback
• Log in
• Open a replay
• Create a focus region
Expected: Playback to only occur inside the selected region
Actual: whole replay will run durring playback
Affected test: [Assert focus play bar](https://app.qawolf.com/test/cl0llq50e151510450sesmnv5s99)
[Replay](https://app.replay.io/recording/focus-mode-not-constraining-playback--2bed8ad1-dd87-4232-9234-33f72a306f67)

[Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1654720063333749)

**Comment by gideonred** [comment]
This ticket has been moved to [FE-215](https://linear.app/replay/issue/FE-215/bug-on-devtools-focus-region-not-constraining-playback)

**Comment by jaril** [comment]
This test needs updating. Pinged QA Wolf to revise the test: https://replayio.slack.com/archives/C02GEJCC9JP/p1654720063333749
