### ISSUE TITLE
:bug: on DevTools: Tool tip for breakpoints failing to lo...

### ISSUE THREAD

**Issue by jperl** [replayio/devtools#7105]
:bug: on DevTools: Tool tip for breakpoints failing to load
• Log in
• Navigate to a replay
• Find a source
• Hover a line to bring up breakpoint tool tip
Expected: tool tip to load
Actual: Tool tip stuck on "Loading.."
Affected tests: [Assert console error on Replays with 1000+ console messages](https://app.qawolf.com/test/ckz7kni7y16626152qqker2w2a2), [Breakpoint panel 500+ hits warning](https://app.qawolf.com/test/ckyf2ajm8000009maadns2p5w)
[Replay](https://app.replay.io/recording/breakpoint-tool-tip-failing-to-load--b439963f-97cb-47df-98e0-3a40d503968d)

[Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1654721503331089)

**Comment by markerikson** [comment]
Could be legit based on the recent changes to breakpoints and analyses

**Comment by gideonred** [comment]
This ticket has been moved to [FE-216](https://linear.app/replay/issue/FE-216/bug-on-devtools-tool-tip-for-breakpoints-failing-to-lo)

**Comment by jaril** [comment]
Deleting breakpoint panel 500+ hits warning, and fixing the console error test: https://replayio.slack.com/archives/C02GEJCC9JP/p1654721503331089.
