### ISSUE TITLE
Recording-specific prefs are not applied

### ISSUE THREAD

**Issue by hbenl** [replayio/devtools#7109]
We are storing some recording-specific prefs in our `asyncStore` (i.e. IndexedDB), but they're not applied when reloading the recording. This also seems to break the breakpoints-07 e2e test because that test reloads the example recording and expects the same primary panel to be selected after the reload.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-217](https://linear.app/replay/issue/FE-217/recording-specific-prefs-are-not-applied)
