### ISSUE TITLE
Logpoint panel shows unfiltered results while loading the filtered ones

### ISSUE THREAD

**Issue by hbenl** [replayio/devtools#7111]
After entering a filter condition for a logpoint, the logpoint panel shows the unfiltered results until the filtered ones are loaded:
https://app.replay.io/recording/logpoint-panel-shows-unfiltered-points--365e5a7c-b867-4dad-80e6-ff7f79e3b994

**Comment by gideonred** [comment]
This ticket has been moved to [FE-218](https://linear.app/replay/issue/FE-218/logpoint-panel-shows-unfiltered-results-while-loading-the-filtered)
