### ISSUE TITLE
Investigate `ValueFront` usage and possible alternatives

### ISSUE THREAD

**Issue by markerikson** [replayio/devtools#7116]
As part of the "new architecture" investigation work, I'm going to review the `ValueFront` class (and possibly `NodeFront` / `Pause` classes as well), document their purpose / usage / behavior, and try to come up with some possible alternative implementation approaches we can consider.

**Comment by gideonred** [comment]
This ticket has been moved to [FE-221](https://linear.app/replay/issue/FE-221/investigate-valuefront-usage-and-possible-alternatives)
