### ISSUE TITLE
Remember Viewer/DevTools state

### ISSUE THREAD

**Issue by souporserious** [replayio/devtools#7123]
**Description:**
When refreshing the page it will move back to the Viewer tab even if the previous tab was DevTools.

**Steps to Reproduce:**
1. Visit a replay
2. Switch to DevTools
3. Refresh and you'll be back at the Viewer page

**Expected Result:**
We remember the page you were previously on when refreshing.

**Comment by hbenl** [comment]
This is one of the effects of #7109 / [FE-217](https://linear.app/replay/issue/FE-217/recording-specific-prefs-are-not-applied). Closing as duplicate.

**Comment by hbenl** [comment]
I was wrong about this being a duplicate so I recreated this issue, this time in Linear: [FE-231](https://linear.app/replay/issue/FE-231/remember-viewerdevtools-state)
