### ISSUE TITLE
Add right padding to console scroll area

### ISSUE THREAD

**Issue by souporserious** [replayio/devtools#7143]
**Description:**
> I feel like there should be some padding-right here to make room for the scrollbar (and maybe make the scrollbar always visible?). Because the line number is blue, I thought it was a hyperlink, and when I went to click on it, the scrollbar captured my click and scrolled. It was very disorienting. - @erikras

**Steps to Reproduce:**
Visit the console in the Replay browser / Firefox and see that the scrollbar covers view source links.

**Expected Result:**
The scrollbar area should have enough right padding that keeps elements away from the scrollbar.

* Screenshots:
![image](https://user-images.githubusercontent.com/2762082/173105758-aaa14ac3-cdd6-4630-a30f-77554b0a8b6e.png)

**Comment by erikras** [comment]
This is tricker than it sounds. The solution is, or is adjacent to [this](https://stackoverflow.com/a/8101017/103690):
```css
  overflow: -moz-scrollbars-vertical; /* For FF */
  -ms-overflow-y: scroll; /* For IE */
  overflow-y: scroll; /* For others & old IE */
```

**Comment by VaibhavNITK** [comment]
hello, if this issue is still open I would like to contribute in it.

**Comment by shashank-mishra14** [comment]
Hey, this issue seems to be easily resolvable, I'd like this issue to be resolved.

**Comment by Domiii** [comment]
According to @jonbell-lot23 [here](https://github.com/replayio/devtools/pull/8821#issuecomment-1461441878), this is legacy now. Closing the issue.
