### ISSUE TITLE
:bug: on DevTools: Comments outside focus region are stil...

### ISSUE THREAD

**Issue by jperl** [replayio/devtools#7159]
:bug: on DevTools: Comments outside focus region are still enabled
• log in
• navigate to a Replay with comments
• create a focus region that excludes a comment
• attempt to interact with excluded comment
Expected: The comment to be greyed out and disabled
Actual comment is fully active
Affected test: [Assert comments in focus mode](https://app.qawolf.com/test/cl0l6z09u103501450se7oprm2lm)
[Replay](https://app.replay.io/recording/comments-outside-focus-region-are-still-enabled--4b4e6a06-c070-462a-9903-fde0945ecc76)

[Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1655158930035809)

**Comment by jaril** [comment]
Revising the test: https://replayio.slack.com/archives/C02GEJCC9JP/p1655158930035809
