### ISSUE TITLE
:bug: on DevTools: Share button is missing and no reply o...

### ISSUE THREAD

**Issue by jperl** [replayio/devtools#7197]
:bug: on DevTools: Share button is missing and no reply option available in comments
Steps to recreate:
• Log in to Replay
• Open a replay ([https://devtools-i727dclqt-recordreplay.vercel.app/recording/sample-folder-visual-studio-code-insi[…]823763437554336007621&amp;time=16000&amp;hasFrames=true](https://devtools-i727dclqt-recordreplay.vercel.app/recording/sample-folder-visual-studio-code-insiders--99215af1-7f6f-4db2-84e4-7a2ea6142240?point=32127336818069823763437554336007621&amp;time=16000&amp;hasFrames=true#))
• BUG: Share button isn’t visible
• Click video and post a comment
• BUG: No reply option on posted comment
Expected: Expected to see a share button to the left of Viewer at the top of the page, also expected to see a reply option once comment is made
Results: No share button and no reply option in comments.

Affected tests: [Comment: create, edit, reply and delete](https://app.qawolf.com/test/ckxgq33mn000008l33ax8h1dc?suite_id=cl4hnfd79159016953p5qqsxk5z6)

Replay video capture: [https://app.replay.io/recording/replay--d2028173-2ac4-4592-b59e-01cdec628f49?point=[…]98257041498214605265556&amp;time=43129.88387096774&amp;hasFrames=false](https://app.replay.io/recording/replay--d2028173-2ac4-4592-b59e-01cdec628f49?point=71394081879098257041498214605265556&amp;time=43129.88387096774&amp;hasFrames=false#)

[Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1655427148267609)

**Comment by jasonLaster** [comment]
cc @bvaughn this might be a regression from the recent comments changes

**Comment by bvaughn** [comment]
@jasonLaster The video shows the user is not signed in. We intentionally don't show the Reply button in that case, or allow adding comments, because it leads to a bad user flow:
1. Click "Reply"
2. Write some text
3. Hit "Enter"
4. App re-directs you to sign in
5. Your text is lost
