### ISSUE TITLE
WebGL Support

### ISSUE THREAD

**Issue by ryota-murakami** [replayio/devtools#7256]
**Description:**
WebGL use to various game sdk like [phaser](https://www.npmjs.com/package/phaser) and some graphical/chart library like [three](https://www.npmjs.com/package/three).

Recently I was join game development that called generally Web3/NTF, This is basically React app but Replay.io is shutdown if "phaser" library is loaded with the message prompt "WebGL is not supported."  

Game if one of the hardest genre about debugging and some graphical effect library might use WebGL a little bit.  

How heavy effort need for adding WebGL support on Replay Protocol?

**Comment by jasonLaster** [comment]
We're tracking this here https://github.com/replayio/gecko-dev/issues/58
