### ISSUE TITLE
Trivial - missing application icon on Windows

### ISSUE THREAD

**Issue by OngeUK** [replayio/devtools#7405]
**Description:**
Replay application is missing an icon on Windows. A generic icon is shown instead

**Steps to Reproduce:**
Open Replay on Windows and observe the taskbar

**Expected Result:**
For the Replay application to have its logo/icon shown

* Screenshots:
![image](https://user-images.githubusercontent.com/28577020/179486778-1b6c36e2-d9a4-4123-bbf0-1e132f1b720f.png)

**Comment by jasonLaster** [comment]
closing as a dupe, but hope to get to it soon
