### ISSUE TITLE
:bug: on Staging: Converting activity to reminder makes t...

### ISSUE THREAD

**Issue by jperl** [replayio/devtools#7444]
:bug: on Staging: Converting activity to reminder makes the reminder date 1 day behind.
Steps to recreate:
• Log in to Replay
• Open up Replay (Time Travel)
• Go to DevTools
• Ctrl + P and search for demo-script.js
• Pause information
• Click the + button along a line to dropdown more information
Expected: To see a lock icon once the line is dropped down for more information (+)
Results: The lock :lock: icon doesn’t display until refresh, inside Replay the lock icon would never appear at all.

Affected tests: [Permissions - DevTools: Assert user role not able to edit print statements](https://app.qawolf.com/test/ckzzwfwf880459950kvzpumjuxr?suite_id=cl600sls0514305nil5unz0v3u)
Link to [Replay](https://app.replay.io/recording/replay--57f51e2e-dd25-4b0e-a8ad-6edf0afdf3df?point=3245185537763463853528397224345909&amp;time=1516&amp;hasFrames=false#)
Attached video of lock being intermittent within QA Platform (Chromium)

[Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1658711248217569)

**Comment by jasonLaster** [comment]
It looks like a developer is logged in here so they should be able to edit the expression
https://app.replay.io/recording/replay--57f51e2e-dd25-4b0e-a8ad-6edf0afdf3df?point=58737858220117525866782252683232103&time=24682.5311286844&hasFrames=true#
