### ISSUE TITLE
Update Marko syntax highlighting

### ISSUE THREAD

**Issue by jasonLaster** [replayio/devtools#7535]
The codemirror syntax highlighting mode should be updated to reflect grammar improvements

https://github.com/marko-js/marko-tmbundle/blob/master/syntaxes/marko.tmLanguage.json

**Comment by SahilDahekar** [comment]
hey @jasonLaster can i work on this issue ? I am beginner to this community looking for good first issues. Also can u elaborate the issue

**Comment by jasonLaster** [comment]
@SahilDahekar go for it

For context, marko is a JS framework with its own syntax that would be nice to support

**Comment by SahilDahekar** [comment]
do i need to add some regex in the above json file for solving this issue @jasonLaster

**Comment by bvaughn** [comment]
This issue is no longer relevant. We stopped using that parsing technique a few months ago.
