### ISSUE TITLE
:bug: on Deploy Production: Clicking “Node modules” check...

### ISSUE THREAD

**Issue by jperl** [replayio/devtools#7621]
:bug: on Deploy Production: Clicking “Node modules” checkbox does not change list of console logs
Steps to Repro:
• log-in
• nav to any test
• nav to DevTools
• within the console’s checkboxes, uncheck “Errors”
• note how many messages are in the console log
• check “Node modules”
Expected: The console’s messages would disappear because none are node modules
Current: The messages remain regardless of “Node modules” being checked or unchecked
Affected Test(s): [Developer: hide node modules](https://app.qawolf.com/test/cl1xtdpfq57245650nfc301x2cf)
[Replay link](https://app.replay.io/recording/clicking-node-modules-checkbox-does-not-change-list-of-console-logs--c52d5caf-d4f6-4b3d-96e8-1def7f01e019?point=38942226440604371795119693962938103&amp;time=13945.339648173209&amp;hasFrames=false)

[Auto posted from QA Wolf Slack message](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1661461255855419)

**Comment by ryanjduffy** [comment]
@bvaughn - Is this related to the new console?

**Comment by bvaughn** [comment]
Not that I can tell.

I'm not sure what the expected outcome of this test is. The logs in the console all come from `demo-script.js` which is served from `static.replay.io` (not `node_modules`). Both the new and old console react the same:

[Kapture 2022-08-26 at 08.43.42.webm](https://user-images.githubusercontent.com/29597/186906144-5afde72e-b734-4b26-8e24-103517d93e95.webm)

**Comment by bvaughn** [comment]
Are they perhaps expecting to see _exceptions_? (They have not enabled those in the Replay they've recorded, but that may be an area where the two consoles differ.)
