### ISSUE TITLE
Events in the console could be displayed better

### ISSUE THREAD

**Issue by Andarist** [replayio/devtools#7719]
**Description:**

At the moment only the constructor's name is displayed
<img width="654" alt="Screenshot 2022-09-12 at 23 31 53" src="https://user-images.githubusercontent.com/9800850/189762368-7edce684-eb23-405e-bcd2-a4d0a41624d1.png">

It's even quite hard to get to the `.target` when expanding this:
<img width="573" alt="Screenshot 2022-09-12 at 23 33 40" src="https://user-images.githubusercontent.com/9800850/189762608-6aa2aa98-f4bf-410d-9d22-3d4a64df5cb7.png">

It's buried deep and can't even be inspected

**Expected Result:**

I should have easy access to the `.target`. The old console was actually displaying this quite nicely:
<img width="375" alt="Screenshot 2022-09-12 at 11 11 07" src="https://user-images.githubusercontent.com/9800850/189762958-7f0c18c0-0c7b-439e-b2f5-95ebaa141621.png">

Note that I didn't have to expand anything here to immediately see the `.target`

**Comment by bvaughn** [comment]
Filed as FE-725.
