### ISSUE TITLE
Get Help links to a bad URL

### ISSUE THREAD

**Issue by programbo** [replayio/devtools#8279]
**Description:**
The  Help > Get help menu item links to https://docs.replay.io/docs#firefox-help 

<img width="860" alt="image" src="https://user-images.githubusercontent.com/1026196/205815924-93a0ca77-3d69-4198-b194-3dc252e978d3.png">

**Steps to Reproduce:**
Select Help > Get help from the hamburger menu

**Expected Result:**
Go to [Replay docs](https://docs.replay.io)

**Additional Context:**
Is this the Firefox help path on the Replay docs domain?

* Screenshots:
* Video (Loom): https://www.loom.com/share/7bb5ef445e2a4f94b8f6c2f939b50558

**Comment by jasonLaster** [comment]
@programbo great catch. These firefox URLs are easy to miss

**Comment by msaini0r** [comment]
@programbo this issue can be closed.
