### ISSUE TITLE
Migrate remaining uses of React-Redux `connect` to function components

### ISSUE THREAD

**Issue by markerikson** [replayio/devtools#8769]
Filed internally as FE-1222 , but copying this publicly since there's some external interest in contributing.

We currently have roughly 50 uses of `connect(`) and 10 uses of `React.Component` (with or without React. ).  I'd love to modernize all of those so that we are exclusively using the React-Redux hooks API and React function components.

Some of the remaining components will likely be tricky due to having more complex logic inside the classes, such as `<SourcesTree>`.  We can leave those for last.

A good first step would be to compile a list of all remaining files that use `connect` or class components so we know which ones need to be updated.

**Comment by ChaiWithJai** [comment]
Checking through the `devtools` repository I only see XX imports and invocations of `connect` from `react-redux`. 

Here's the breakdown - 10 usages within `client/debugger`.

```
App
QuickOpenModal
Tabs
PrimaryPanes/index
QuickOpenButton
SourcesTrees
Breakpoint
BreakpointHeading
Popover
```

2 usages on 2 dynamic pages:

```
[...view].tsx
[...id].tsx
```

34 usages across 33 files in `ui/components`

```
src/ui/components/App.tsx
src/ui/components/DevTools.tsx
src/ui/components/KeyboardShortcuts.tsx
src/ui/components/SkeletonLoader.tsx
src/ui/components/WaitForReduxSlice.tsx
src/ui/components/CommandPalette/CommandPalette.tsx
src/ui/components/Comments/CommentMarker.tsx
src/ui/components/Comments/index.tsx
src/ui/components/Comments/VideoComments/CommentsOverlay.tsx
src/ui/components/Events/Events.tsx
src/ui/components/Events/ReplayInfo.tsx
src/ui/components/Header/ShareButton.tsx
src/ui/components/Header/UserOptions.tsx
src/ui/components/NetworkMonitor/index.tsx
src/ui/components/shared/Error.tsx
src/ui/components/shared/LaunchBrowserModal.tsx
src/ui/components/shared/LaunchButton.tsx
src/ui/components/shared/LoadingScreen.tsx
src/ui/components/shared/LoomModal.tsx
src/ui/components/shared/Modal.tsx
src/ui/components/shared/NewAttachment.tsx
src/ui/components/shared/PrivacyModal.tsx
src/ui/components/shared/TeamOnboarding.tsx
src/ui/components/shared/FirstReplayModal/FirstReplayModal.tsx
src/ui/components/shared/Modals/SourcemapSetupModal.tsx
src/ui/components/shared/NewWorkspaceModal/NewWorkspaceModal.tsx
src/ui/components/shared/OnboardingModal/DownloadReplayModal.tsx
src/ui/components/shared/OnboardingModal/OnboardingModal.tsx
src/ui/components/shared/OnboardingModal/SingleInviteModal.tsx
src/ui/components/shared/SharingModal/SharingModal.tsx
src/ui/components/shared/UserSettingsModal/UserSettingsModal.tsx
src/ui/components/shared/WorkspaceSettingsModal/WorkspaceMember.tsx
src/ui/components/Timeline/Marker.tsx
```

And as for Class components I see 14 usages across 13 files:

```
src/devtools/client/debugger/src/components/A11yIntention.js
src/devtools/client/debugger/src/components/shared/Modal.js
src/devtools/client/debugger/src/components/shared/tree.tsx
src/devtools/client/debugger/src/workers/parser/tests/fixtures/frameworks/reactComponentEs5.js
src/devtools/client/inspector/boxmodel/components/BoxModelMain.tsx
src/devtools/client/inspector/layout/components/LayoutApp.tsx
src/devtools/client/inspector/rules/components/DeclarationValue.tsx
src/devtools/client/inspector/rules/components/Selector.tsx
src/devtools/client/shared/components/Accordion.tsx
src/devtools/client/shared/components/splitter/Draggable.tsx
src/ui/components/Comments/CommentMarker.tsx
src/ui/components/shared/Confetti.js
src/ui/components/Timeline/Marker.tsx
```

**Comment by ChaiWithJai** [comment]
Of the Class-based components most seem like straightforward migrations and the only ones that I would keep an eye on are:

1. `Draggable`:  This components is using a reference to attach event listeners to. However, these references aren't being cleaned up or handled in the component lifecycle.
2. `Tree`: At a cursory glance, my first guess is that this component is using a technique to minimize the number of elements rendered onto the DOM based on the user's scroll position and size of the viewport because there's is likely a performance concern here of having too many elements rendered onto the DOM. This is going to be a fun one IMO.
3. `Realistic`: like `Draggable` could also have a stale closure as its accepting an `animationInstance` property. However, there's only one invocation of this component in `StatusDropdown` so this should be fairly easy to write an integration test on and then smoke test.
4. `Marker` is rendering a "red circle" throughout the timeline I believe. There's a `shouldComponentUpdate` lifecycle hook here that is likely here because of a performance optimization reason.

I would imagine that these 4 components will require some integration testing. The remaining 9 components might be able to use a codemod to upgrade.

**Comment by markerikson** [comment]
Nice work!  I think there _are_ a few more uses of `React.Component`, just without the `React.` prefix - if you search for the text `extends Component` I think I see another 13-ish.

Some of these will be trickier than others, such as `Tree` and `SourcesTree`.  Anything that's got a significant amount of logic in it can be left until last.

**Comment by markerikson** [comment]
I think a good approach here might be:

- Start by migrating some of the _function_ components that use `connect` over to use the hooks instead
- Migrate some of the simpler class components to function components.  If it's easy enough to migrate them to hooks in the same PR, do so, otherwise just do the function component conversion first, then circle back and do the `connect` -> hook conversion later.
- Skip the very large and complex class components for now - we can tackle those last.  (and if really necessary, just leave them as-is.  For example, that `Tree` component dates back to the original FF DevTools codebase.  It works, and we really don't have a reason to go rewrite it.)

**Comment by ChaiWithJai** [comment]
> Nice work! I think there are a few more uses of React.Component, just without the React. prefix - if you search for the text extends Component I think I see another 13-ish.

You're absolutely on the money here. There's 8 components extending Component and 7 more extending PureComponent.

**Comment by markerikson** [comment]
Also, please come by the Discord - happy to chat about this more directly as well!  https://replay.io/discord .  I spend most of my time in the `#frontend` channel.

**Comment by jasonLaster** [comment]
Bet copilot labs could help here 😉

**Comment by bvaughn** [comment]
Closing in favor of FE-1222.
