### ISSUE TITLE
Loom style emoji comments

### ISSUE THREAD

**Issue by jasonLaster** [replayio/devtools#8787]
### Discussed in https://github.com/replayio/devtools/discussions/4603

<div type='discussions-op-text'>

<sup>Originally posted by **jasonLaster** November 20, 2021</sup>

I wonder if loom style emoji comments might be a fun lightweight way to callout interesting times in the timeline

<img width="1177" alt="Screen Shot 2021-11-20 at 10 52 15 AM" src="https://user-images.githubusercontent.com/254562/142737984-48cef5ab-6b8e-47cc-ba5e-75d79357b966.png">

<img width="921" alt="emojis" src="https://user-images.githubusercontent.com/254562/142737977-1498f621-c33b-4123-89f0-7feb3d2898fa.png">
</div>

**Comment by jonbell-lot23** [comment]
See also https://github.com/replayio/devtools/issues/8793, which could be related

**Comment by manavagr1108** [comment]
Hey there, I was working on this issue and wanted a small doubt about the implementation, So I just wanted to make sure, let's say I am commenting on the replay. Now only I have permission to set the emoji. In short (it is not like GitHub reaction emojis, where anyone is allowed to add emojis to the comment). Here we are trying to assign emojis for comments to make the time look interesting and to distinguish between comments.

**Comment by manavagr1108** [comment]
Ok sorry if I wasn't clear enough, I just need to clarify one small confusion. Lets say I comment on the replay, so only I have the access to `add/update/remove` the `icon/emoji` for that particular comment or any one can update the comment's `icon/emoji` ?

**Comment by manavagr1108** [comment]
Thank you for the confirmation. Hey @jonbell-lot23 I have completed implementing this feature by like 80-90%. I am stuck with one place that is updating the comments using Graph QL I am nt able to query and update the value. Can you please help if possible?

**Comment by jonbell-lot23** [comment]
> Thank you for the confirmation. Hey @jonbell-lot23 I have completed implementing this feature by like 80-90%. I am stuck with one place that is updating the comments using Graph QL I am nt able to query and update the value. Can you please help if possible?

I apologise, I don't have a strong understanding of that part of the code and the rest of the team is pretty heads-down right now. Someone might offer help, but I can't promise anything.

**Comment by manavagr1108** [comment]
Ohh, no problem @jonbell-lot23, I will try to fix it up by myself. Thankyou for your time.

**Comment by bvaughn** [comment]
Hi. Sorry. I’m just seeing this issue. I have similar reservations as with #8793.

It is ok to prototype this, if you are interested, but such a prototype would almost certainly not be merged.

Comments are structured- not just JSON blobs:
https://github.com/replayio/backend/blob/424de44b48c75fa0b0eb03522c102697fe92c5ab/src/graphql-api/schema.ts#L180

New functionality like we’re describing in this issue would require a new top level attribute (and a change to the GraphQL schema). It wouldn’t just be something we bolted on.

@manavagr1108 if you have already started working on a prototype and you would like to share it with us, please do feel free to! I think it’s best we close this issue so others aren’t confused by it though.
