### ISSUE TITLE
Jump back to prior pause

### ISSUE THREAD

**Issue by jasonLaster** [replayio/devtools#8788]
We started it here, https://github.com/replayio/devtools/pull/7767

**Comment by hungngo04** [comment]
Hi, can I work on this?

**Comment by jasonLaster** [comment]
@hungngo04 go for it. This is a fun one :)

**Comment by VaibhavNITK** [comment]
Is this issue still open ? Can i work on it?

**Comment by jasonLaster** [comment]
@VaibhavNITK feel free to

**Comment by bvaughn** [comment]
This issue isn't super well-defined, particularly since it's tagged as "good first issue", so I'm going to close it to avoid confusing people who are new to the project 😄  Looks like the functionality will be landing soon, via #8898 though!
