### ISSUE TITLE
Open source the fuzzer

### ISSUE THREAD

**Issue by jasonLaster** [replayio/devtools#8791]
### Discussed in https://github.com/replayio/devtools/discussions/4820

<div type='discussions-op-text'>

<sup>Originally posted by **jasonLaster** December 10, 2021</sup>
There are a couple of reasons why we should open source the fuzzer

1. The fuzzer is an important part of the story on how we improved the quality of our backend
2. The fuzzer is an example of how you can use our node api 
3. The fuzzer will help others better understand the protocol and do more interesting things 
4. Open sourcing the fuzzer will help us share our ProtocolClient and other utils which wraps the npm package.
</div>

Happy to share the fuzzer source code with anyone interested in running with this.

**Comment by JaydenTeoh** [comment]
@jasonLaster Hi, I would love to work on this. Would you mind sharing the fuzzer source code with me and I'll take a crack at making it open source?

**Comment by Rohan-Dah** [comment]
Heyyy... Is this issue still open? Would love to work on it..

**Comment by jasonLaster** [comment]
@JaydenTeoh @Rohan-Dah here's a gist
https://gist.github.com/jasonLaster/b693ea2ca9a0a2f327befb9256aadbc4

I think it could use the `node-client` we have in the packages directory

**Comment by Rohan-Dah** [comment]
Hey @jasonLaster  ... I researched a bit about the working of fuzzers and procedures to make it open source...  The image I have in my mind is 
‘Making the fuzzer open source means you intend to add it to any of the open sourced directories in the project so that reasons you mentioned above will be achieved and the output generated by the fuzzer will be cross-checked'
Am I getting it correct?

**Comment by jasonLaster** [comment]
I think it'd be sufficient if we had a new repo which had this script and we could run it directly. The key is that it'll also need the code that's in the `node-client` package too. Honestly, this might be too big/open ended for a good first issue

**Comment by Rohan-Dah** [comment]
Alright cool🙌
