### ISSUE TITLE
Add Comment Categories

### ISSUE THREAD

**Issue by Domiii** [replayio/devtools#8793]
Comments currently look cluttered. It would be great if we can more easily visually distinguish them with: (i) color scheme and (ii) icon:

* When creating a console message, let user choose one of a small set of categories:
  * `Bug`
  * `Breadcrumb`
  * `Question`
  * `Info`
  * (maybe others, feel free to discuss)
* A comment's category should be used to change the message's (i) color scheme (generally, a set of CSS rules) and (ii) icon
* In order to allow for this to work without DB changes, simply use a prefix or an emoji in the first few characters of the comment to make the distinction.
* This should work in dark- and light-mode.

**Comment by PavitraAgarwal21** [comment]
Can I work on it

**Comment by jasonLaster** [comment]
@PavitraAgarwal21 go for it

**Comment by Domiii** [comment]
The beautiful thing about a proposal is that anyone can take a crack at it. Don't forget to post your own version here to allow for evaluation.

**Comment by jasonLaster** [comment]
@jonbell-lot23 it might be nice to take a stab at our own emoji/category picker. Probably similar in spirit to our unicorn picker too

<img width="935" alt="Screenshot 2023-02-23 at 7 44 17 AM" src="https://user-images.githubusercontent.com/254562/220924869-5c599ef8-89cf-4943-9e7d-b656eb8de174.png">

**Comment by Domiii** [comment]
@jasonLaster Should this be merged with #8787 since this proposes icons for comments, which are going to be necessary for #8787 to even work?
(Jon also pointed out the connection)

**Comment by jonbell-lot23** [comment]
The two solutions could overlap but don't have to. I'd keep them separate and see what people come up with.

(I sometimes assign two designers the same task specifically to see different implementations of the same design insight. This is the same concept.)

**Comment by anikdhabal** [comment]
I have to idea in order to add comment categories-
1>when someone wants to add comment then a list of comment categories appear at the time of clicking. After that the color scheme and icon should add according to users' selection.
 OR
2.There should be comment categories option in the commentcard. After choosing the category user can add comment, then the color scheme and icon add accordingly.

Suggest me some idea.

**Comment by Domiii** [comment]
@anikdhabal Show your idea. That's how prototypes work 🤓 
If you are on the fence as to whether this is worth your time, then it probably isn't.
If you want feedback, then show what you got.

**Comment by jasonLaster** [comment]
@anikdhabal It'd be nice if this feature worked similarly to print statement prefixes
https://docs.replay.io/reference-guide/print-statements#6ff496b1e71e47e3a5952a0c7252db45

Another analolgy would be discord reactions where a button appears on hover

**Comment by anikdhabal** [comment]
okk let me try

**Comment by Roaster05** [comment]
![Replay IO Issue8793](https://user-images.githubusercontent.com/100672872/221498177-020e51c3-51c8-474b-8d5d-5cb89f1827f1.png)

I have worked on a Prototype for this issue which is similar to the Better Comments Extension where the comments are identified using the initial special character for different categories 
I will appreciate your feedbacks regarding the same

**Comment by jasonLaster** [comment]
Thanks @Roaster05 perhaps a good place to start that does not involve too much design would be to add emoji support to the comment editor. This would work like Github's emoji picker and is probably already a Lexical plugin.

**Comment by Domiii** [comment]
My personal opinion is: 

1. Have you ever used Replay? I strongly recommend every potential contributor to get some experience with it first. [Here are some good examples](https://gotbugs.vercel.app/).
2. My two cents on the design (as a non-designer, but as a Replay-user): When you view someone else's Replay, see how the comments feel. See if you can guess what the Replay's author's intent was? How can your design help the viewer direct attention to the important things? How can we reduce the cluttery feeling of the comments with this new custom appearance?

**Comment by Roaster05** [comment]
> Thanks @Roaster05 perhaps a good place to start that does not involve too much design would be to add emoji support to the comment editor. This would work like Github's emoji picker and is probably already a Lexical plugin.

I was also thinking to implement a prototype which is similar to Github issues where we can add labels to comments which will help in figuring out what the comment is trying to convey

**Comment by akshat-vashistha** [comment]
@jasonLaster @Domiii @jonbell-lot23 I am willing to work on this issue, can you please assign it to me?

**Comment by Domiii** [comment]
@akshat-vashistha, we do not assign issues to external contributors because there is no system of accountability in place. If you want to take it on, feel free to. If you don't, then don't.

**Comment by Aimajoke** [comment]
This is similar of what @Roaster05 proposed, but I kinda also like the idea of etiquetes, similar to what github does with the issues.
![WhatsApp Image 2023-03-18 at 12 54 07 AM](https://user-images.githubusercontent.com/78597533/226088534-6c7487e1-4dae-41dc-b42a-adde2b9b645b.jpeg)
The menu appears on click
![WhatsApp Image 2023-03-18 at 12 54 09 AM](https://user-images.githubusercontent.com/78597533/226088535-def12a81-888b-4e8b-9fc5-dc7e24b405c8.jpeg)

It is coded for save the style with the comment as a prefix to not require changes in db, I would have been better to hide it, but I could not get it, lexical was a greater wall than what I expected, and was hard just to came to this.
Another thing that bothered me was that comment changes are saved on blur, and a save button do not exist, and there is the editmode that enable made changes on the comment, but it close itself onblur so I did a crappy thing to save the style with a useEffect to make it work, the battle with lexical was hard as you see haha.
The last thing is that I did not create a dark-mode style, it probably was simple but a couple hours ago I read about the cancellation of your participation on gsoc and I got pretty sad so wanted to push this early and see what can I do now, also the dark etiquete of tailwind did not do the job and its already 1am hahaha.

**Comment by bvaughn** [comment]
This shouldn't be tagged as "good first issue"

IMO comment categorization needs to be an attribute on the Comment type, which would require backend and GraphQL changes. I don't agree with the proposed "_prefix or an emoji in the first few characters of the comment_". Sorry folks 🙇🏼

**Comment by bvaughn** [comment]
Going to close this until we've had a chance to discuss it internally (via DE-425)
