### ISSUE TITLE
Review keyboard handling of `Enter` to ensure numpad `Enter` key works

### ISSUE THREAD

**Issue by markerikson** [replayio/devtools#8796]
I was testing out the new editable hit counts field in https://github.com/replayio/devtools/pull/8736 , edited the numbers with the number pad on my keyboard, and tried to apply it with the number pad `Enter` key.  Nothing happened.  Repeated this a few times before I happened to try the main keyboard `Enter` key, which worked.

It looks like we're checking for `event.code === "Enter"`, and it seems like the two different `Enter` keys result in different event.code values of "Enter" vs "NumpadEnter":

https://w3c.github.io/uievents/tools/key-event-viewer.html

![image](https://user-images.githubusercontent.com/1128784/220710693-55cf572d-aea4-4dc9-ab24-80f2803c36a1.png)

We've got about 10-ish other places we do `case "Enter"` in our codebase. It would be good to double-check if these work, and figure out a better approach for handling both keys.

**Comment by BabyElias** [comment]
Hey, so we need to ensure that both different enter keys produce the same output right?

**Comment by Abhishek-1337** [comment]
I would like to work on this issue.

**Comment by PavitraAgarwal21** [comment]
can I work on this issue .

**Comment by jasonLaster** [comment]
@BabyElias, @Abhishek-1337, @PavitraAgarwal21 feel free to run w/ it. It's fine if there are multiple PRs :)

**Comment by PramodhTVK** [comment]
Where can I find other relevant details with regard to this issue?
