### ISSUE TITLE
Edit Contributing.md

### ISSUE THREAD

**Issue by anikdhabal** [replayio/devtools#8799]
**Description:**
In contributing.md step given to run Replay locally is--

git clone git@github.com:RecordReplay/devtools.git
yarn install
yarn start

But sometime there was a problem occur called-Could not find a production build in the '........\.next' directory. So the solution is before yarn start ,It is required to run yarn dev or yarn build.

**Steps to Reproduce:**
git clone git@github.com:RecordReplay/devtools.git
yarn install
yarn start

**Expected Result:**
http://localhost:8080 should working.
**Additional Context:**
<img width="821" alt="Screenshot 2023-02-23 012015" src="https://user-images.githubusercontent.com/81948346/220745342-129055fb-6bef-4947-9323-2f09d35c4088.png">

* Screenshots:
* Video (Loom):
* Replay ([replay.io/record-bugs](https://replay.io/record-bugs) for instructions):

**Comment by anikdhabal** [comment]
so can I work on this?

**Comment by markerikson** [comment]
We're probably best suited to update the contributing docs :)  We'll try to do that shortly.
