### ISSUE TITLE
Submit Feedback returns a 404 | Page not found

### ISSUE THREAD

**Issue by msaini0r** [replayio/devtools#8806]
**Description:**

The Submit feedback returns a 404 | Page could not be found. Similar issue related to #8279

**Steps to Reproduce:**

 Open the Replay Browser, go to dropdown menu --> Help --> Submit feedback

**Expected Result:**

I think it should redirect to discord or email. 

**Additional Context:**

* Video (Loom):

https://user-images.githubusercontent.com/87536360/220826706-49f3b463-33e9-4824-a6c1-f5bb9ae1719e.mp4

**Comment by bvaughn** [comment]
Thanks for reporting this, @msaini0r!

This repository is for the Replay web interface. The bug you've reported is with the browser itself, which has no public facing GitHub repository. I've filed an internal issue about this though (RUN-1427).

**Comment by Domiii** [comment]
@msaini0r, please keep it where it belongs. No need to file extra issues.
You already got accepted and will be merged here: https://github.com/replayio/gecko-dev/pull/959
