### ISSUE TITLE
No scrollbar is present in inspector-sidebar-container

### ISSUE THREAD

**Issue by anikdhabal** [replayio/devtools#8820]
**Description:**

No scrollbar is present in inspector-sidebar-container. It is difficult to scroll horizontally as well as vertically.
**Steps to Reproduce:**
1.open Replay browser
2.Open Elements in Devtools
3.try to scroll Rules, Layout or computed list. 

**Expected Result:**
Scrollbar should be  there in order to see the complete list.
**Additional Context:**

* Screenshots:
* 
![Screenshot 2023-02-24 180446 (3)](https://user-images.githubusercontent.com/81948346/221687695-6d22f049-cab4-4f46-a7ef-b915715f70b2.jpg)

* Video (Loom):
* Replay ([replay.io/record-bugs](https://replay.io/record-bugs) for instructions):

**Comment by anikdhabal** [comment]
@jasonLaster can you check this.

**Comment by jasonLaster** [comment]
I think this is expected if there is no mouse

**Comment by anikdhabal** [comment]
If there is a mouse also the same issue occurred.
![scroollbar_issue](https://user-images.githubusercontent.com/81948346/221767330-22d23ed3-5ba7-4a77-a43e-aa78970a939a.jpeg)

**Comment by anikdhabal** [comment]
<img width="716" alt="Screenshot 2023-02-28 115220" src="https://user-images.githubusercontent.com/81948346/221770202-7dfed3ec-5492-4b39-9ab7-5067a2a893e9.png">

I think this would be the proposed solution @jasonLaster

**Comment by Domiii** [comment]
hi @anikdhabal,

This looks like a design change. Without being a designer, I have a few concerns:

1. The scrollbars are way too big. Can you find other scrollbars in the app and see if they are also this big? Not sure if this is intended or not.
2. I am not sure why you are hardcoding `height` to `220px` but its generally bad practice. I can imagine you found it in other places in the code? If so, please refer/link to where you found it. Also, see if you can find a better place to adapt from, where we are not hardcoding pixel values?
3. You did not go through the guidelines checklist before committing. We added that recently. For example, it asks you to run lint/prettier. Please always check all items before submitting a PR.

**Comment by Roaster05** [comment]
> hi @anikdhabal,
> 
> This looks like a design change. Without being a designer, I have a few concerns:
> 
> 1. The scrollbars are way too big. Can you find other scrollbars in the app and see if they are also this big? Not sure if this is intended or not, but I'd say, it should not be like that.
> 2. I am not sure why you are hardcoding `height` to `220px` but its generally bad practice to hardcode pixel values. I can imagine you found it in other places in the code? If so, please refer/link to where you found it. Also, see if you can find a better place to adapt from, where we are not hardcoding pixel values.
> 3. You did not go through the contributor guidelines checklist before committing. We added that recently. For example, the guidelines ask you to run lint/prettier. Please always check all items before submitting a PR.

hey @Domiii 
Thanks for reviewing my PR and your feedback and here is my response:

Yes there are other scrollbars also present in the Console and Elements section and they are having the scrolling feature but these scrolling feature was also set for the inspector-sidebar container but was relatively set and was not working properly
like for the computed component its styling for the container was mentioned in the file `src/devtools/client/themes/computed.css` but was relative as we can see in
` #computed-container {
  overflow: auto;
  height: 100%;
}` still there wasn't any scrolling feature so i tried hardcoding the value using `px` so that it can work ,It is also working using other relative styling units like `em`,`rem`,or `vh` so if you want i can commit these changes in a new commit
Also i am really sorry for not running the lint, prettier test will make sure to take care of these things from now on
Thanks

**Comment by Domiii** [comment]
@Roaster05 I think the scrollbar DPI issue has been moved to here: https://github.com/replayio/devtools/issues/8905

**Comment by Roaster05** [comment]
> @Roaster05 I think the scrollbar DPI issue has been moved to here: #8905

Ig this issue was related to the width of the scrollbar but the issue i am talking about is that there aren't any scrollbars present in the Elements panel of the devtools and most of the contents get hidden

**Comment by Aimajoke** [comment]
> > @Roaster05 I think the scrollbar DPI issue has been moved to here: #8905
> 
> Ig this issue was related to the width of the scrollbar but the issue i am talking about is that there aren't any scrollbars present in the Elements panel of the devtools and most of the contents get hidden
Yup, it seems like while solving this issue they found another related to scrollbar width, this one is still unsolved

**Comment by Aimajoke** [comment]
> Ig this issue was related to the width of the scrollbar but the issue i am talking about is that there aren't any scrollbars present in the Elements panel of the devtools and most of the contents get hidden


Yup, it seems like while solving this issue they found another one related with scrollbar width or DPI, this one about scrollbar not showing still unsolved

**Comment by Aimajoke** [comment]
@Domiii Is it okay with this solution for the issue?, the thicc scrollbar is not part of it as had moved to other issue

**Comment by bvaughn** [comment]
Fixed by #8922
