### ISSUE TITLE
Show opened file option is not working properly

### ISSUE THREAD

**Issue by anikdhabal** [replayio/devtools#8830]
**Description:**
Show opened file option is not working properly. It sometime shows a list of files that have not been opened.

**Steps to Reproduce:**
Open up 10 different source file tabs in the DevTools

**Expected Result:**
Only opened file should be in the list.
**Additional Context:**

* Screenshots:
* 
<img width="1080" alt="Screenshot 2023-02-26 132835" src="https://user-images.githubusercontent.com/81948346/221399668-dfc27f4a-a13b-4062-aa3d-329eafa6630e.png">

* Video (Loom):
* Replay ([replay.io/record-bugs](https://replay.io/record-bugs) for instructions):
* https://app.replay.io/recording/show-opened-file--85a83041-65da-4b93-b11c-a368642851d9

**Comment by jasonLaster** [comment]
Thanks @anikdhabal if you record a replay of the bug, I can leave some comments where I think the bug is occuring

**Comment by bvaughn** [comment]
I think this is a misunderstanding. That list is not supposed to be just open files.
