### ISSUE TITLE
Library section focus outline clipped

### ISSUE THREAD

**Issue by anikdhabal** [replayio/devtools#8838]
**Description:**
Done and Edit  button's border is not positioned properly . when click the done or Edit button ,the border is not fully visible.

* Screenshots:
<img width="1093" alt="Screenshot 2023-02-28 030418" src="https://user-images.githubusercontent.com/81948346/221690688-8efe08ef-233a-4233-9d90-01a652b102be.png">

<img width="1080" alt="Screenshot 2023-02-28 233358" src="https://user-images.githubusercontent.com/81948346/221939972-468f1777-9008-4ee0-a4b9-e38fa67269ba.png">

* Video (Loom):
* Replay ([replay.io/record-bugs](https://replay.io/record-bugs) for instructions):
* https://app.replay.io/recording/border-is-not-fully-visible-when-clicked--10c39501-ab18-4d74-b29c-926b83aa56d3

**Comment by jasonLaster** [comment]
cc @jaril

**Comment by Andrew-Doghry** [comment]
![button_issue](https://user-images.githubusercontent.com/121642489/221933191-78a15cf8-e37b-4c61-a2bd-9fdf2aaca96d.jpeg)
actually there is no problem with that button on replay browser !

**Comment by anikdhabal** [comment]
@Andrew-Doghry just click the button then see result. I'm talking about the border of this button.

**Comment by Roaster05** [comment]
> ![button_issue](https://user-images.githubusercontent.com/121642489/221933191-78a15cf8-e37b-4c61-a2bd-9fdf2aaca96d.jpeg) actually there is no problem with that button on replay browser !

there is an issue when we press the button it just because of less margin from right side, I have pushed an repo for the same .

**Comment by anikdhabal** [comment]
@jaril please give some review

**Comment by Domiii** [comment]
@anikdhabal It seems like not everyone agrees that this is an issue. There is an easy way to figure this out though. Produce a replay, add comments in the relevant places, so everyone can see it. Then, if you want, fix it and in the PR provide a Replay of where the problem is solved.

**Comment by anikdhabal** [comment]
https://app.replay.io/recording/border-is-not-fully-visible-when-clicked--10c39501-ab18-4d74-b29c-926b83aa56d3
@Domiii

**Comment by anikdhabal** [comment]
![WhatsApp Image 2023-03-09 at 4 56 24 PM](https://user-images.githubusercontent.com/81948346/224009877-7885398a-504d-405a-a6b6-2962678efdb7.jpeg)

Problem is in the container. If we add margin then the issue is resolved.

**Comment by bvaughn** [comment]
This looks like a valid bug. (Thanks for the Replay!) The proposed fix PR got closed because it was failing Lint though. Happy to review another fix though.

**Comment by anikdhabal** [comment]
> This looks like a valid bug. (Thanks for the Replay!) The proposed fix PR got closed because it was failing Lint though. Happy to review another fix though.

Thanks for you review.
