### ISSUE TITLE
Update contributing.md

### ISSUE THREAD

**Issue by anikdhabal** [replayio/devtools#8842]
**Description:*
To setup Replay we have to run cp .env.sample .env before yarn dev in terminal. Or it is showing Error.

**Steps to Reproduce:**
1.Setup Replay to contribute
2.Open http://localhost:8080 after yarn dev.

* Screenshots:
* 
<img width="1080" alt="Screenshot 2023-02-28 122003" src="https://user-images.githubusercontent.com/81948346/221778095-40d37a87-e512-43c0-aff6-616b42b57baa.png">

* Video (Loom):
* Replay ([replay.io/record-bugs](https://replay.io/record-bugs) for instructions):

**Comment by aryans1319** [comment]
I would like to work on this issue.
Can you assign this to me?

**Comment by anikdhabal** [comment]
@jasonLaster please review it.

**Comment by Aimajoke** [comment]
In addition the link provided to start using replay in localhost is broken, it would be better to match the entire getting started section with the one on the readme.md of the project.

-Screenshots
![image](https://user-images.githubusercontent.com/78597533/223547851-87583173-f9f3-4a4e-b672-016bfe7b1642.png)

![image](https://user-images.githubusercontent.com/78597533/223547312-f44edca6-b8f7-432d-9f78-6ec69e29e225.png)

**Comment by bvaughn** [comment]
Fixed via 1b7a5eeee
