### ISSUE TITLE
The timeline starts from 30:00 rather than from 00:00

### ISSUE THREAD

**Issue by swapn652** [replayio/devtools#8889]
**Description:**
The timeline below should start from 00:00, right? But it starts from 30:00

**Steps to Reproduce:**
Just record any replay and play it.

* Screenshots:
![image](https://user-images.githubusercontent.com/70851202/223431347-d0d805c2-54ef-4190-b2b6-2f16757d8b74.png)

* Video (Loom):
* Replay ([replay.io/record-bugs](https://replay.io/record-bugs) for instructions):

**Comment by manavagr1108** [comment]
Even I have been facing this issue, and this issue is cause to fail few test when we run `yarn test`.

**Comment by ryanjduffy** [comment]
I suspect this is a locale issue which doesn't repro for everyone. [Create a Replay](https://replay.io/record-bugs) of the problem and share it here and we can debug it together!

**Comment by swapn652** [comment]
https://app.replay.io/recording/clock--8effe23f-01a8-46cb-b377-db9278c0aa7f
Here's a replay.

![image](https://user-images.githubusercontent.com/70851202/223475413-3eda1f74-89e4-429d-92da-ea1131542dab.png)
As you can see, the timeline shows 30:00-30:09

**Comment by ryanjduffy** [comment]
I should have been more clear create a replay of _you viewing that replay in your locale_ and share _that_ here. Since the issue is locale-specific, I can't repro it (without changing my locale). And though I could do that, one of the great value propositions of Replay is that others don't have to repro the bug if you can share a replay of it!

**Comment by swapn652** [comment]
Oh alright I get it now

**Comment by ryanjduffy** [comment]
That's great but I meant you should use the Replay browser to create a replay of the issue and not just a video of the bug.

Make sense?

**Comment by swapn652** [comment]
Sorry, but I am kinda confused on what you want. Can you please, record a video yourself and show me, so that I can understand on what exactly you want?

**Comment by Domiii** [comment]
@swapn652, I am sure you and Ryan are already quiet frustrated about this. Let me try to explain it one more time:
1. If you want to debug any website, you can use Replay to record it, and then replay that recording in Replay devtools (that is on `app.replay.io`, or on `localhost`, if you are running them locally).
2. That means that you can also use Replay to debug Replay devtools. That is what Ryan is asking you to do:
3. Open the buggy Replay in your Replay browser and record it. Then post the link here (after making it public of course).

I usually call it "Replayception".

**Comment by swapn652** [comment]
Ty @Domiii, I finally get it now.

**Comment by swapn652** [comment]
https://app.replay.io/recording/clockreplay--1a13a10a-356c-45ce-aad3-f39e42d58f99
Here you go.

**Comment by adarsh-sgh** [comment]
> I suspect this is a locale issue

yupp, that's the case. my timezone is +5 : 30 so  it's showing 30 in minutes while converting 0 milliseconds to minutes.

can I open a PR fixing this ?

**Comment by Domiii** [comment]
@adarsh-sgh Sure, go ahead. No need to ask. Don't forget to check our contributor guidelines before submitting. Good luck!
