### ISSUE TITLE
 Scrollbar Size is too wide inside Replay Browser and Firefox in windows

### ISSUE THREAD

**Issue by anikdhabal** [replayio/devtools#8905]
**Description:**
 scrollbar issue on High DPI screen. Scrollbar of Replay is too wide inside Replay Browser and Firefox in window. But it's fine in  another browser.

**Steps to Reproduce:**
1.Open Replay in Replay browser or Firefox in Windows.
2.See scrollbar

**Expected Result:**
Its size should be perfect.

**Additional Context:**

* Screenshots:
<img width="716" alt="221770202-7dfed3ec-5492-4b39-9ab7-5067a2a893e9" src="https://user-images.githubusercontent.com/81948346/224034182-89d8ec1d-c70e-4cff-8b11-3dd90898c582.png">

* Video (Loom):
* Replay ([replay.io/record-bugs](https://replay.io/record-bugs) for instructions):
https://app.replay.io/recording/scrollbar-dpi-issue--d446af32-6cea-4d45-9ae5-f40d3439aefe

**Comment by swapn652** [comment]
I think this issue exists only in replay browser.

### Here's a screenshot of Replay in Microsoft Edge
![image](https://user-images.githubusercontent.com/70851202/224051957-5d70a8ff-fc4a-44c4-b5c3-739cdd8edd36.png)

### Local Host
![image](https://user-images.githubusercontent.com/70851202/224052673-b8abbf68-6398-4c1d-9623-20c27135ab44.png)

### Replay Browser
![image](https://user-images.githubusercontent.com/70851202/224052761-76c55ea9-ce01-48cb-a4ef-8eaa71b414d8.png)

**Comment by swapn652** [comment]
I wonder why that happens. The code responsible for scroll bar is in **src/base.css**. Apparently the code isn't working for replay browser.

**Comment by Domiii** [comment]
The current "Replay Browser" is based on Firefox. So maybe its a Firefox thing.

**Comment by anikdhabal** [comment]
> The current "Replay Browser" is based on Firefox. So maybe its a Firefox thing.

Yes, currently **::-webkit-scrollbar** is not supported by firefox. Currently, styling scrollbars for Firefox is available with **scrollbar-width** and **scrollbar-color** properties.
