### ISSUE TITLE
Unable to scroll horizontally in scope panel

### ISSUE THREAD

**Issue by marvinhagemeister** [replayio/devtools#8911]
**Description:**

I'm unable to scroll horizontally in the "Scopes" panel. I can only scroll vertically. This makes it difficult to see longer string values or HTML elements.

<img width="418" alt="Screenshot 2023-03-09 at 23 38 36" src="https://user-images.githubusercontent.com/1062408/224176347-62f200d2-206e-4925-b1df-f72624ebe3dc.png">

**Steps to Reproduce:**

**Expected Result:**

**Additional Context:**

* Screenshots:
* Video (Loom):
* Replay ([replay.io/record-bugs](https://replay.io/record-bugs) for instructions):

**Comment by jasonLaster** [comment]
Nice catch. cc @hbenl

**Comment by bvaughn** [comment]
> I'm unable to scroll horizontally in the "Scopes" panel.

FWIW this was intentional and mirrors Chrome's behavior. FWIW you can right-click and copy values.

(I think there was also some kind of weird edge-case scrolling interaction that it helped avoid too but it's been too long to remember)

**Comment by bvaughn** [comment]
Going to close this as a known issue for now.
