### ISSUE TITLE
Videos in documentation don't work in Firefox

### ISSUE THREAD

**Issue by marvinhagemeister** [replayio/devtools#8913]
**Description:**

Not sure if this is the right issue tracker.

Videos on https://docs.replay.io/workflows/recording-bug-reports don't work in Firefox in macOS.

<img width="1349" alt="Screenshot 2023-03-09 at 23 49 37" src="https://user-images.githubusercontent.com/1062408/224178210-9aedeeda-fde5-4a63-a1f0-9b160d595c8b.png">

**Steps to Reproduce:**

**Expected Result:**

**Additional Context:**

* Screenshots:
* Video (Loom):
* Replay ([replay.io/record-bugs](https://replay.io/record-bugs) for instructions):

**Comment by anikdhabal** [comment]
can you Record a Replay and share it?

**Comment by oops408** [comment]
![image](https://user-images.githubusercontent.com/68081409/227453342-5bd6d968-b413-41a3-b965-fb265acfc20a.png)

Chrome user, same issue.

**Comment by jasonLaster** [comment]
Apparently Notion changed their API. should be an easy fix

**Comment by remorses** [comment]
This issue should be fixed now.

**Comment by bvaughn** [comment]
Working for me in Chrome, Firefox, and Safari. Thanks!
