### ISSUE TITLE
Update README.md for yarn v3 specific information

### ISSUE THREAD

**Issue by xoldyckk** [replayio/devtools#8942]
**Description:**
[Setup instructions](https://github.com/replayio/devtools#setup-instructions) section of README.md suggests global installation of yarn using `npm i -g yarn`. This is incorrect as this script results in installation of yarn `v1.22.19` which has reached end of life. Replay devtools make use of yarn v3 which is not backwards compatible with yarn v1. 

The official installation instructions for yarn v3 list a different approach for [installation](https://yarnpkg.com/getting-started/install). This should be mentioned in this repo's README.md.

**Steps to Reproduce:**
1. Run `npm i -g yarn`
2. Run `yarn -v`
3. Yarn version printed out is `1.22.19` which is the latest release of yarn v1.

**Expected Result:**
README.md should point to correct installation instructions for yarn v3.

**Additional Context:**
Lemme know if there's something I misunderstood. I'd like to be assigned to this issue, I'll submit a PR shortly after the maintainer's approval for this issue.

* Screenshots:
![Screenshot_20230315_155918](https://user-images.githubusercontent.com/82873939/225282267-efe55a96-2535-46a1-8d55-8efed93d40de.png)

* Video (Loom):
* Replay ([replay.io/record-bugs](https://replay.io/record-bugs) for instructions):

**Comment by markerikson** [comment]
FWIW, the instructions as listed _are_ valid.  Yarn v2 and v3 work by having v1 installed globally first.  Then, you add the v3 "binary JS" file to the repo + a config file.  When you run `yarn` in the repo, v1 starts, sees the v3 config file, and then kicks off v3 to do the real work.

The `corepack` thing is another way to get Yarn v1 installed globally, but it ends up with the same result as `npm i -g yarn`.

We can probably tweak the wording there, but the general approach is correct as listed.

**Comment by xoldyckk** [comment]
@markerikson Please take a look at this https://yarnpkg.com/getting-started/install

**Comment by markerikson** [comment]
@xoldyckk : I'm 98% sure, based on all my usage experience, that if you were to follow the Corepack instructions on a fresh machine, and then run `yarn -v` in a random folder it would print out `1.22.x`.

**Comment by xoldyckk** [comment]
@markerikson Nope it installed yarn berry v3.

**Comment by markerikson** [comment]
Hmm. I'm very surprised by that.  All my experience with Yarn so far, across multiple repos, has been that you needed 1.x installed globally to bootstrap into 3.x local to the repo.

FWIW, I _know_ that approach works. So, I don't think there's anything we actually need to change here.
