### ISSUE TITLE
Input disabled message in console is formatted strangely

### ISSUE THREAD

**Issue by ryanjduffy** [replayio/devtools#8945]
**Description:**
When the console is narrow and the user is paused outside the focus window, the input disabled message is formatted strangely

**Steps to Reproduce:**
https://app.replay.io/recording/input-disabled-message-formatting-issue--0ff423cc-6eef-41bc-9d99-5af7d884e266

**Expected Result:**

**Additional Context:**

* Screenshots:
* Video (Loom):
* Replay ([replay.io/record-bugs](https://replay.io/record-bugs) for instructions):

**Comment by MohitGupta14** [comment]
Hi, I found a similar  Issue. At the bottom right corner, PurchaseForm.tsx looks weird when we scroll. 
I want to know that should  I create this as a new issue and make a PR. I'm new to open-Source, and need some guidance.
 
https://user-images.githubusercontent.com/81846020/225627578-f5c83f20-400f-48a0-9f6d-46ac7e472bc1.mp4

**Comment by bvaughn** [comment]
Hey 👋🏼  We use Linear rather than GitHub to track frontend work so I missed this issue. I did notice, and fix, the underlying problem yesterday in PR #8949 though so I'm going to close this.
