### ISSUE TITLE
No MenuBar Icon in Windows 10

### ISSUE THREAD

**Issue by primeagen-rustaceans** [replayio/devtools#9289]
**Description:**
I installed replay on windows 10. I ran replay from cmd prompt by running the executable. There is no Icon in the menu bar. 

**Steps to Reproduce:**

**Expected Result:**

**Additional Context:**

* Screenshots:
![Replay](https://github.com/replayio/devtools/assets/115938518/1880f62d-c734-4acb-ae31-96fd925929e5)

* Video (Loom):
* Replay ([replay.io/record-bugs](https://replay.io/record-bugs) for instructions):

**Comment by bvaughn** [comment]
Hi 👋🏼  This repository is where the Replay devtools _website_ code lives. The Replay _browser_ code (what you're reporting this issue in) lives in another repository: https://github.com/replayio/gecko-dev/issues
