### ISSUE TITLE
[FE-1647] [FE-1623] The Cypress Panel should stay in sync

### ISSUE THREAD

**Issue by jasonLaster** [replayio/devtools#9414]
I think the video explains this pretty well, but the short version is that the Cy panel should stay in sync with the replay timeline.

This means that when you move to a new time, the blue left border should update and the selected step should be cleared

[https://www.loom.com/share/62332445d9b442d4abfac904a0604740](https://www.loom.com/share/62332445d9b442d4abfac904a0604740)

<sub>From [SyncLinear.com](https://synclinear.com) | [FE-1623](https://linear.app/replay/issue/FE-1623/the-cypress-panel-should-stay-in-sync)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [FE-1623](https://linear.app/replay/issue/FE-1623/the-cypress-panel-should-stay-in-sync)</sub>

**Comment by jasonLaster** [comment]
@bvaughn why do you think it's a dupe?

**Comment by bvaughn** [comment]
@jasonLaster I don't know what this "sync linear" thing is but two duplicate Linear issues were created:
https://linear.app/replay/issue/FE-1623
https://linear.app/replay/issue/FE-1623

Literally word for word copies, so I closed the newer one.

Whatever the "sync linear" thing is apparently closed the other one _and_ this GitHub issue.

**Comment by bvaughn** [comment]
You can see the title of this GitHub issue even mentions two Linear issues: "[FE-1647] [FE-1623]"

**Comment by jasonLaster** [comment]
That's fine. Hopefully Playwright can catch up

**Comment by jasonLaster** [comment]
I think we should clear the selected step when you jump to a new point in time. The Before|After hud also doesnt make sense when you're viewing a different point in time

**Comment by jasonLaster** [comment]
by the way I just tested this change and it's already 10x better being able to see the current progress.

Related, we should also scroll the panel so that when you jump to a new point in time we show the closest steps as well. This is similar to what we do in the console and will soon do in redux as well.

**Comment by jasonLaster** [comment]
Thanks for the write up. Lets find a time to discuss tomorrow.
