### ISSUE TITLE
Unable to render www.underarmour.com properly

### ISSUE THREAD

**Issue by kshehadeh** [replayio/devtools#9592]
**Description:**
I'm not seeing www.underarmour.com render properly in Replay.io

**Steps to Reproduce:**
Navigate to www.underarmour.com

See this:
<img width="1481" alt="image" src="https://github.com/replayio/devtools/assets/107061/468bc00b-9dc1-4d19-846a-7f7100c78992">

**Expected Result:**
<img width="1277" alt="image" src="https://github.com/replayio/devtools/assets/107061/09a6aef9-3181-45b9-a2d3-7c10dcce920d">

**Additional Context:**

* Screenshots: (see above)
* Video (Loom):
* Replay ([replay.io/record-bugs](https://replay.io/record-bugs) for instructions): https://app.replay.io/recording/under-armourr-official-store-or-free-shipping-available--1b2f634f-ab33-4575-9a91-964b13cf0a9d

**Comment by ryanjduffy** [comment]
This is unfortunately an issue with the upstream version of Firefox on which we're based (v91). We're in the process of migrating to chromium as our interactive recorder so it's unlikely we'll rebase firefox to pick up the fix. If you're up for trying the pre-release version of chromium, check out our [docs on Installing Replay Chromium](https://docs.replay.io/bug-reports/installing-the-replay-browser/installing-replay-chrome) and let us know how it goes!
